; Generated by Ripple C99 Compiler (rcc)

getchar:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 8 slots for locals
    ADDI SP, SP, 8
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
    LI S3, 1
    ADD A0, S3, R0
    LI S2, 0
    ADD A1, S2, R0
    LI S1, 0
    ADD A2, S1, R0
    LI S0, 0
    ADD A3, S0, R0
; Spill live registers before call
; Spill const_f0_op0_1 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 8
    STORE S3, SB, SC
; Spill const_f0_op1_0 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S2, SB, SC
; Spill const_f0_op2_0 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Spill const_f0_op3_0 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 4 register arguments
; Arg 0 (scalar) to A0
; Arg 1 (scalar) to A1
; Arg 2 (scalar) to A2
; Arg 3 (scalar) to A3
; Call function ros_int21
    CALL ros_int21
; Scalar return value for t0
; Copy Rv0 to allocatable T7
    ADD T7, RV0, R0
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_getchar_99999
L_getchar_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
