; Generated by Ripple C99 Compiler (rcc)

in_range:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 0
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_in_range_2
; Branch to L_in_range_2 if condition is false
    BEQ R0, R0, L_in_range_1
; Unconditional branch to L_in_range_1 (condition was true)
; Invalidated 2 alloca bindings
L_in_range_1:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 255
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_in_range_3
; Unconditional branch to L_in_range_3
; Invalidated 2 alloca bindings
L_in_range_2:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_in_range_3
; Unconditional branch to L_in_range_3
; Invalidated 1 alloca bindings
L_in_range_3:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_in_range_99999
L_in_range_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isdigit:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isdigit_4:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 48
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_isdigit_6
; Branch to L_isdigit_6 if condition is false
    BEQ R0, R0, L_isdigit_5
; Unconditional branch to L_isdigit_5 (condition was true)
; Invalidated 2 alloca bindings
L_isdigit_5:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 57
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_isdigit_7
; Unconditional branch to L_isdigit_7
; Invalidated 2 alloca bindings
L_isdigit_6:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_isdigit_7
; Unconditional branch to L_isdigit_7
; Invalidated 1 alloca bindings
L_isdigit_7:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_isdigit_99999
L_isdigit_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
islower:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_islower_8:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 97
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_islower_10
; Branch to L_islower_10 if condition is false
    BEQ R0, R0, L_islower_9
; Unconditional branch to L_islower_9 (condition was true)
; Invalidated 2 alloca bindings
L_islower_9:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 122
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_islower_11
; Unconditional branch to L_islower_11
; Invalidated 2 alloca bindings
L_islower_10:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_islower_11
; Unconditional branch to L_islower_11
; Invalidated 1 alloca bindings
L_islower_11:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_islower_99999
L_islower_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isupper:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isupper_12:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 65
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_isupper_14
; Branch to L_isupper_14 if condition is false
    BEQ R0, R0, L_isupper_13
; Unconditional branch to L_isupper_13 (condition was true)
; Invalidated 2 alloca bindings
L_isupper_13:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 90
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_isupper_15
; Unconditional branch to L_isupper_15
; Invalidated 2 alloca bindings
L_isupper_14:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_isupper_15
; Unconditional branch to L_isupper_15
; Invalidated 1 alloca bindings
L_isupper_15:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_isupper_99999
L_isupper_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isalpha:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isalpha_16:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t3 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function islower
    CALL islower
; Scalar return value for t4
; Copy Rv0 to allocatable T7
    ADD T7, RV0, R0
    LI T6, 0
    XOR T5, T7, T6
    LI T4, 0
    SLTU T7, T4, T5
    BEQ T7, R0, L_isalpha_17
; Branch to L_isalpha_17 if condition is false
    BEQ R0, R0, L_isalpha_18
; Unconditional branch to L_isalpha_18 (condition was true)
L_isalpha_17:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op6_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T2, SB, T3
; Spill live registers before call
; Spill t6 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T2, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Call function isupper
    CALL isupper
; Scalar return value for t7
; Copy Rv0 to allocatable T1
    ADD T1, RV0, R0
    LI T0, 0
    XOR S3, T1, T0
    LI S1, 0
    SLTU T1, S1, S3
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE T1, SB, S2
    BEQ R0, R0, L_isalpha_19
; Unconditional branch to L_isalpha_19
; Invalidated 1 alloca bindings
L_isalpha_18:
    LI S0, 1
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    STORE S0, SB, T5
    BEQ R0, R0, L_isalpha_19
; Unconditional branch to L_isalpha_19
; Invalidated 1 alloca bindings
L_isalpha_19:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op13_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T4, FP, R0
    ADDI T4, T4, 1
    LOAD T6, SB, T4
    MOVE RV0, T6
; Jump to epilogue
    BEQ R0, R0, L_isalpha_99999
L_isalpha_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isalnum:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isalnum_20:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t3 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function isalpha
    CALL isalpha
; Scalar return value for t4
; Copy Rv0 to allocatable T7
    ADD T7, RV0, R0
    LI T6, 0
    XOR T5, T7, T6
    LI T4, 0
    SLTU T7, T4, T5
    BEQ T7, R0, L_isalnum_21
; Branch to L_isalnum_21 if condition is false
    BEQ R0, R0, L_isalnum_22
; Unconditional branch to L_isalnum_22 (condition was true)
L_isalnum_21:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op6_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T2, SB, T3
; Spill live registers before call
; Spill t6 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T2, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Call function isdigit
    CALL isdigit
; Scalar return value for t7
; Copy Rv0 to allocatable T1
    ADD T1, RV0, R0
    LI T0, 0
    XOR S3, T1, T0
    LI S1, 0
    SLTU T1, S1, S3
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE T1, SB, S2
    BEQ R0, R0, L_isalnum_23
; Unconditional branch to L_isalnum_23
; Invalidated 1 alloca bindings
L_isalnum_22:
    LI S0, 1
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    STORE S0, SB, T5
    BEQ R0, R0, L_isalnum_23
; Unconditional branch to L_isalnum_23
; Invalidated 1 alloca bindings
L_isalnum_23:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op13_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T4, FP, R0
    ADDI T4, T4, 1
    LOAD T6, SB, T4
    MOVE RV0, T6
; Jump to epilogue
    BEQ R0, R0, L_isalnum_99999
L_isalnum_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isblank:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isblank_24:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f12_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 32
    XOR T6, S0, T7
    LI T5, 1
    SLTU S0, T6, T5
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_isblank_25
; Branch to L_isblank_25 if condition is false
    BEQ R0, R0, L_isblank_26
; Unconditional branch to L_isblank_26 (condition was true)
; Invalidated 2 alloca bindings
L_isblank_25:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f12_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 9
    XOR T5, T0, T6
    LI T7, 1
    SLTU T0, T5, T7
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_isblank_27
; Unconditional branch to L_isblank_27
; Invalidated 2 alloca bindings
L_isblank_26:
    LI S1, 1
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_isblank_27
; Unconditional branch to L_isblank_27
; Invalidated 1 alloca bindings
L_isblank_27:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f12_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_isblank_99999
L_isblank_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isspace:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 14 slots for locals
    ADDI SP, SP, 14
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isspace_28:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
    ADD S0, FP, R0
    ADDI S0, S0, 2
    ADD T7, FP, R0
    ADDI T7, T7, 3
    ADD T6, FP, R0
    ADDI T6, T6, 4
    ADD T5, FP, R0
    ADDI T5, T5, 5
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op2_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T4, SB, S2
    LI T3, 32
    XOR T2, T4, T3
    LI T1, 1
    SLTU T4, T2, T1
    LI T0, 0
    XOR T2, T4, T0
    LI T1, 0
    SLTU T4, T1, T2
    BEQ T4, R0, L_isspace_29
; Branch to L_isspace_29 if condition is false
    BEQ R0, R0, L_isspace_30
; Unconditional branch to L_isspace_30 (condition was true)
; Invalidated 6 alloca bindings
L_isspace_29:
; Load instruction: t10 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op8_t10 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T2, SB, T3
    LI T1, 12
    XOR T0, T2, T1
    LI T4, 1
    SLTU T2, T0, T4
    LI T5, 0
    XOR T6, T2, T5
    LI T7, 0
    SLTU T2, T7, T6
; Recompute alloca t6 at FP+5
    ADD S0, FP, R0
    ADDI S0, S0, 5
    STORE T2, SB, S0
    BEQ R0, R0, L_isspace_31
; Unconditional branch to L_isspace_31
; Invalidated 2 alloca bindings
L_isspace_30:
    LI S1, 1
; Recompute alloca t6 at FP+5
    ADD S2, FP, R0
    ADDI S2, S2, 5
    STORE S1, SB, S2
    BEQ R0, R0, L_isspace_31
; Unconditional branch to L_isspace_31
; Invalidated 1 alloca bindings
L_isspace_31:
; Load instruction: t13 = load FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op17_t13 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t6 at FP+5
    ADD T0, FP, R0
    ADDI T0, T0, 5
    LOAD T4, SB, T0
    LI T1, 0
    XOR T6, T4, T1
    LI T7, 0
    SLTU T4, T7, T6
    BEQ T4, R0, L_isspace_32
; Branch to L_isspace_32 if condition is false
    BEQ R0, R0, L_isspace_33
; Unconditional branch to L_isspace_33 (condition was true)
; Invalidated 1 alloca bindings
L_isspace_32:
; Load instruction: t15 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op21_t15 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T5, FP, R0
    LOAD T3, SB, T5
    LI S0, 10
    XOR S1, T3, S0
    LI S2, 1
    SLTU T3, S1, S2
    LI T6, 0
    XOR T7, T3, T6
    LI T1, 0
    SLTU T3, T1, T7
; Recompute alloca t5 at FP+4
    ADD T4, FP, R0
    ADDI T4, T4, 4
    STORE T3, SB, T4
    BEQ R0, R0, L_isspace_34
; Unconditional branch to L_isspace_34
; Invalidated 2 alloca bindings
L_isspace_33:
    LI T0, 1
; Recompute alloca t5 at FP+4
    ADD S1, FP, R0
    ADDI S1, S1, 4
    STORE T0, SB, S1
    BEQ R0, R0, L_isspace_34
; Unconditional branch to L_isspace_34
; Invalidated 1 alloca bindings
L_isspace_34:
; Load instruction: t18 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op30_t18 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t5 at FP+4
    ADD S2, FP, R0
    ADDI S2, S2, 4
    LOAD S0, SB, S2
    LI T7, 0
    XOR T1, S0, T7
    LI T6, 0
    SLTU S0, T6, T1
    BEQ S0, R0, L_isspace_35
; Branch to L_isspace_35 if condition is false
    BEQ R0, R0, L_isspace_36
; Unconditional branch to L_isspace_36 (condition was true)
; Invalidated 1 alloca bindings
L_isspace_35:
; Load instruction: t20 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op34_t20 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T5, SB, T4
    LI T0, 13
    XOR S1, T5, T0
    LI T1, 1
    SLTU T5, S1, T1
    LI T6, 0
    XOR T7, T5, T6
    LI S0, 0
    SLTU T5, S0, T7
; Recompute alloca t4 at FP+3
    ADD S2, FP, R0
    ADDI S2, S2, 3
    STORE T5, SB, S2
    BEQ R0, R0, L_isspace_37
; Unconditional branch to L_isspace_37
; Invalidated 2 alloca bindings
L_isspace_36:
    LI S1, 1
; Recompute alloca t4 at FP+3
    ADD T1, FP, R0
    ADDI T1, T1, 3
    STORE S1, SB, T1
    BEQ R0, R0, L_isspace_37
; Unconditional branch to L_isspace_37
; Invalidated 1 alloca bindings
L_isspace_37:
; Load instruction: t23 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op43_t23 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+3
    ADD T0, FP, R0
    ADDI T0, T0, 3
    LOAD T7, SB, T0
    LI S0, 0
    XOR T6, T7, S0
    LI T4, 0
    SLTU T7, T4, T6
    BEQ T7, R0, L_isspace_38
; Branch to L_isspace_38 if condition is false
    BEQ R0, R0, L_isspace_39
; Unconditional branch to L_isspace_39 (condition was true)
; Invalidated 1 alloca bindings
L_isspace_38:
; Load instruction: t25 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op47_t25 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD S2, FP, R0
    LOAD S1, SB, S2
    LI T1, 9
    XOR T6, S1, T1
    LI T4, 1
    SLTU S1, T6, T4
    LI S0, 0
    XOR T7, S1, S0
    LI T0, 0
    SLTU S1, T0, T7
; Recompute alloca t3 at FP+2
    ADD T6, FP, R0
    ADDI T6, T6, 2
    STORE S1, SB, T6
    BEQ R0, R0, L_isspace_40
; Unconditional branch to L_isspace_40
; Invalidated 2 alloca bindings
L_isspace_39:
    LI T4, 1
; Recompute alloca t3 at FP+2
    ADD T1, FP, R0
    ADDI T1, T1, 2
    STORE T4, SB, T1
    BEQ R0, R0, L_isspace_40
; Unconditional branch to L_isspace_40
; Invalidated 1 alloca bindings
L_isspace_40:
; Load instruction: t28 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op56_t28 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+2
    ADD T7, FP, R0
    ADDI T7, T7, 2
    LOAD T0, SB, T7
    LI S0, 0
    XOR T6, T0, S0
    LI S2, 0
    SLTU T0, S2, T6
    BEQ T0, R0, L_isspace_41
; Branch to L_isspace_41 if condition is false
    BEQ R0, R0, L_isspace_42
; Unconditional branch to L_isspace_42 (condition was true)
; Invalidated 1 alloca bindings
L_isspace_41:
; Load instruction: t30 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op60_t30 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T1, SB, T4
    LI T6, 11
    XOR S2, T1, T6
    LI S0, 1
    SLTU T1, S2, S0
    LI T0, 0
    XOR T7, T1, T0
    LI S2, 0
    SLTU T1, S2, T7
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T1, SB, S0
    BEQ R0, R0, L_isspace_43
; Unconditional branch to L_isspace_43
; Invalidated 2 alloca bindings
L_isspace_42:
    LI T6, 1
; Recompute alloca t2 at FP+1
    ADD T7, FP, R0
    ADDI T7, T7, 1
    STORE T6, SB, T7
    BEQ R0, R0, L_isspace_43
; Unconditional branch to L_isspace_43
; Invalidated 1 alloca bindings
L_isspace_43:
; Load instruction: t33 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f14_op69_t33 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    LOAD T0, SB, S2
    MOVE RV0, T0
; Jump to epilogue
    BEQ R0, R0, L_isspace_99999
L_isspace_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
iscntrl:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_iscntrl_44:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f16_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t2 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S1, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function in_range
    CALL in_range
; Scalar return value for t3
; Copy Rv0 to allocatable S0
    ADD S0, RV0, R0
    LI T7, 0
    XOR T6, S0, T7
    LI T5, 0
    SLTU S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 1
    SLTU S0, T3, T2
    LI T1, 0
    XOR T0, S0, T1
    LI S3, 0
    SLTU S0, S3, T0
    BEQ S0, R0, L_iscntrl_47
; Branch to L_iscntrl_47 if condition is false
    BEQ R0, R0, L_iscntrl_45
; Unconditional branch to L_iscntrl_45 (condition was true)
L_iscntrl_45:
    LI RV0, 0
; Jump to epilogue
    BEQ R0, R0, L_iscntrl_99999
L_iscntrl_47:
    ADD S2, FP, R0
    ADDI S2, S2, 1
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f16_op10_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD S1, FP, R0
    LOAD T6, SB, S1
    LI T5, 32
    SLT T6, T6, T5
    LI T7, 0
    XOR T3, T6, T7
    LI T2, 0
    SLTU T6, T2, T3
    BEQ T6, R0, L_iscntrl_48
; Branch to L_iscntrl_48 if condition is false
    BEQ R0, R0, L_iscntrl_49
; Unconditional branch to L_iscntrl_49 (condition was true)
; Invalidated 2 alloca bindings
L_iscntrl_48:
; Load instruction: t11 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f16_op14_t11 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T0, SB, T4
    LI S3, 127
    XOR T1, T0, S3
    LI S0, 1
    SLTU T0, T1, S0
    LI T5, 0
    XOR T3, T0, T5
    LI T2, 0
    SLTU T0, T2, T3
; Recompute alloca t7 at FP+1
    ADD T7, FP, R0
    ADDI T7, T7, 1
    STORE T0, SB, T7
    BEQ R0, R0, L_iscntrl_50
; Unconditional branch to L_iscntrl_50
; Invalidated 2 alloca bindings
L_iscntrl_49:
    LI T6, 1
; Recompute alloca t7 at FP+1
    ADD S1, FP, R0
    ADDI S1, S1, 1
    STORE T6, SB, S1
    BEQ R0, R0, L_iscntrl_50
; Unconditional branch to L_iscntrl_50
; Invalidated 1 alloca bindings
L_iscntrl_50:
; Load instruction: t14 = load FatPtr(FatPointer { addr: Temp(7), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(7), bank: Stack })
; LOAD: Pointer load_src_ptr_f16_op23_t14 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t7 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    LOAD T1, SB, S2
    MOVE RV0, T1
; Jump to epilogue
    BEQ R0, R0, L_iscntrl_99999
L_iscntrl_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isprint:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isprint_51:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f18_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 32
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_isprint_53
; Branch to L_isprint_53 if condition is false
    BEQ R0, R0, L_isprint_52
; Unconditional branch to L_isprint_52 (condition was true)
; Invalidated 2 alloca bindings
L_isprint_52:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f18_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 126
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_isprint_54
; Unconditional branch to L_isprint_54
; Invalidated 2 alloca bindings
L_isprint_53:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_isprint_54
; Unconditional branch to L_isprint_54
; Invalidated 1 alloca bindings
L_isprint_54:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f18_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_isprint_99999
L_isprint_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isgraph:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isgraph_55:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f20_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 33
    SLT T6, S0, T7
    LI T5, 1
    SUB S0, T5, T6
    LI T4, 0
    XOR T3, S0, T4
    LI T2, 0
    SLTU S0, T2, T3
    BEQ S0, R0, L_isgraph_57
; Branch to L_isgraph_57 if condition is false
    BEQ R0, R0, L_isgraph_56
; Unconditional branch to L_isgraph_56 (condition was true)
; Invalidated 2 alloca bindings
L_isgraph_56:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f20_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI T6, 126
    SLT T5, T6, T0
    LI T7, 1
    SUB T0, T7, T5
    LI T3, 0
    XOR T2, T0, T3
    LI T4, 0
    SLTU T0, T4, T2
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE T0, SB, S0
    BEQ R0, R0, L_isgraph_58
; Unconditional branch to L_isgraph_58
; Invalidated 2 alloca bindings
L_isgraph_57:
    LI S1, 0
; Recompute alloca t2 at FP+1
    ADD S2, FP, R0
    ADDI S2, S2, 1
    STORE S1, SB, S2
    BEQ R0, R0, L_isgraph_58
; Unconditional branch to L_isgraph_58
; Invalidated 1 alloca bindings
L_isgraph_58:
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f20_op17_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD T5, FP, R0
    ADDI T5, T5, 1
    LOAD T7, SB, T5
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_isgraph_99999
L_isgraph_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
ispunct:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_ispunct_59:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f22_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t3 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function isgraph
    CALL isgraph
; Scalar return value for t4
; Copy Rv0 to allocatable T7
    ADD T7, RV0, R0
    LI T6, 0
    XOR T5, T7, T6
    LI T4, 0
    SLTU T7, T4, T5
    BEQ T7, R0, L_ispunct_61
; Branch to L_ispunct_61 if condition is false
    BEQ R0, R0, L_ispunct_60
; Unconditional branch to L_ispunct_60 (condition was true)
L_ispunct_60:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f22_op6_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T2, SB, T3
; Spill live registers before call
; Spill t6 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T2, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Call function isalnum
    CALL isalnum
; Scalar return value for t7
; Copy Rv0 to allocatable T1
    ADD T1, RV0, R0
    LI T0, 0
    XOR S3, T1, T0
    LI S1, 0
    SLTU T1, S1, S3
    LI S2, 0
    XOR S0, T1, S2
    LI T5, 1
    SLTU T1, S0, T5
    LI T4, 0
    XOR T6, T1, T4
    LI T7, 0
    SLTU T1, T7, T6
; Recompute alloca t2 at FP+1
    ADD T3, FP, R0
    ADDI T3, T3, 1
    STORE T1, SB, T3
    BEQ R0, R0, L_ispunct_62
; Unconditional branch to L_ispunct_62
; Invalidated 1 alloca bindings
L_ispunct_61:
    LI T2, 0
; Recompute alloca t2 at FP+1
    ADD S3, FP, R0
    ADDI S3, S3, 1
    STORE T2, SB, S3
    BEQ R0, R0, L_ispunct_62
; Unconditional branch to L_ispunct_62
; Invalidated 1 alloca bindings
L_ispunct_62:
; Load instruction: t11 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f22_op17_t11 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD S1, FP, R0
    ADDI S1, S1, 1
    LOAD T0, SB, S1
    MOVE RV0, T0
; Jump to epilogue
    BEQ R0, R0, L_ispunct_99999
L_ispunct_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
isxdigit:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 13 slots for locals
    ADDI SP, SP, 13
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_isxdigit_63:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
    ADD S0, FP, R0
    ADDI S0, S0, 2
; Load instruction: t4 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op2_t4 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T7, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE S3, SB, SC
; Spill t4 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE T7, SB, SC
; Set SP = FP+33 so callee frame is above spills
    ADDI SP, FP, 33
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T7, R0
; Call function isdigit
    CALL isdigit
; Scalar return value for t5
; Copy Rv0 to allocatable T6
    ADD T6, RV0, R0
    LI T5, 0
    XOR T4, T6, T5
    LI T3, 0
    SLTU T6, T3, T4
    BEQ T6, R0, L_isxdigit_64
; Branch to L_isxdigit_64 if condition is false
    BEQ R0, R0, L_isxdigit_65
; Unconditional branch to L_isxdigit_65 (condition was true)
L_isxdigit_64:
    ADD T2, FP, R0
    ADDI T2, T2, 3
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op6_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    LI S3, 97
    SLT S1, T0, S3
    LI S0, 1
    SUB T0, S0, S1
    LI S2, 0
    XOR T7, T0, S2
    LI T4, 0
    SLTU T0, T4, T7
    BEQ T0, R0, L_isxdigit_68
; Branch to L_isxdigit_68 if condition is false
    BEQ R0, R0, L_isxdigit_67
; Unconditional branch to L_isxdigit_67 (condition was true)
; Invalidated 2 alloca bindings
L_isxdigit_67:
; Load instruction: t11 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op12_t11 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T5, SB, T3
    LI T6, 102
    SLT S1, T6, T5
    LI S0, 1
    SUB T5, S0, S1
    LI S3, 0
    XOR T7, T5, S3
    LI T4, 0
    SLTU T5, T4, T7
; Recompute alloca t7 at FP+3
    ADD S2, FP, R0
    ADDI S2, S2, 3
    STORE T5, SB, S2
    BEQ R0, R0, L_isxdigit_69
; Unconditional branch to L_isxdigit_69
; Invalidated 2 alloca bindings
L_isxdigit_68:
    LI T0, 0
; Recompute alloca t7 at FP+3
    ADD T1, FP, R0
    ADDI T1, T1, 3
    STORE T0, SB, T1
    BEQ R0, R0, L_isxdigit_69
; Unconditional branch to L_isxdigit_69
; Invalidated 1 alloca bindings
L_isxdigit_69:
; Load instruction: t14 = load FatPtr(FatPointer { addr: Temp(7), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(7), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op21_t14 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t7 at FP+3
    ADD T2, FP, R0
    ADDI T2, T2, 3
    LOAD S1, SB, T2
    LI S0, 0
    XOR T6, S1, S0
    LI T7, 0
    SLTU S1, T7, T6
; Recompute alloca t3 at FP+2
    ADD T4, FP, R0
    ADDI T4, T4, 2
    STORE S1, SB, T4
    BEQ R0, R0, L_isxdigit_66
; Unconditional branch to L_isxdigit_66
; Invalidated 2 alloca bindings
L_isxdigit_65:
    LI S3, 1
; Recompute alloca t3 at FP+2
    ADD T3, FP, R0
    ADDI T3, T3, 2
    STORE S3, SB, T3
    BEQ R0, R0, L_isxdigit_66
; Unconditional branch to L_isxdigit_66
; Invalidated 1 alloca bindings
L_isxdigit_66:
; Load instruction: t16 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op28_t16 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+2
    ADD S2, FP, R0
    ADDI S2, S2, 2
    LOAD T0, SB, S2
    LI T1, 0
    XOR T6, T0, T1
    LI T7, 0
    SLTU T0, T7, T6
    BEQ T0, R0, L_isxdigit_70
; Branch to L_isxdigit_70 if condition is false
    BEQ R0, R0, L_isxdigit_71
; Unconditional branch to L_isxdigit_71 (condition was true)
; Invalidated 1 alloca bindings
L_isxdigit_70:
    ADD S0, FP, R0
    ADDI S0, S0, 4
; Load instruction: t19 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op32_t19 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T2, FP, R0
    LOAD T4, SB, T2
    LI S3, 65
    SLT T3, T4, S3
    LI T6, 1
    SUB T4, T6, T3
    LI T7, 0
    XOR T1, T4, T7
    LI T0, 0
    SLTU T4, T0, T1
    BEQ T4, R0, L_isxdigit_74
; Branch to L_isxdigit_74 if condition is false
    BEQ R0, R0, L_isxdigit_73
; Unconditional branch to L_isxdigit_73 (condition was true)
; Invalidated 2 alloca bindings
L_isxdigit_73:
; Load instruction: t22 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op38_t22 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD S2, FP, R0
    LOAD T3, SB, S2
    LI T6, 70
    SLT S3, T6, T3
    LI T1, 1
    SUB T3, T1, S3
    LI T0, 0
    XOR T7, T3, T0
    LI T4, 0
    SLTU T3, T4, T7
; Recompute alloca t18 at FP+4
    ADD T2, FP, R0
    ADDI T2, T2, 4
    STORE T3, SB, T2
    BEQ R0, R0, L_isxdigit_75
; Unconditional branch to L_isxdigit_75
; Invalidated 2 alloca bindings
L_isxdigit_74:
    LI S0, 0
; Recompute alloca t18 at FP+4
    ADD S3, FP, R0
    ADDI S3, S3, 4
    STORE S0, SB, S3
    BEQ R0, R0, L_isxdigit_75
; Unconditional branch to L_isxdigit_75
; Invalidated 1 alloca bindings
L_isxdigit_75:
; Load instruction: t25 = load FatPtr(FatPointer { addr: Temp(18), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(18), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op47_t25 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t18 at FP+4
    ADD T1, FP, R0
    ADDI T1, T1, 4
    LOAD T6, SB, T1
    LI T7, 0
    XOR T4, T6, T7
    LI T0, 0
    SLTU T6, T0, T4
; Recompute alloca t2 at FP+1
    ADD T2, FP, R0
    ADDI T2, T2, 1
    STORE T6, SB, T2
    BEQ R0, R0, L_isxdigit_72
; Unconditional branch to L_isxdigit_72
; Invalidated 2 alloca bindings
L_isxdigit_71:
    LI S2, 1
; Recompute alloca t2 at FP+1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE S2, SB, S0
    BEQ R0, R0, L_isxdigit_72
; Unconditional branch to L_isxdigit_72
; Invalidated 1 alloca bindings
L_isxdigit_72:
; Load instruction: t27 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f24_op54_t27 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+1
    ADD S3, FP, R0
    ADDI S3, S3, 1
    LOAD T4, SB, S3
    MOVE RV0, T4
; Jump to epilogue
    BEQ R0, R0, L_isxdigit_99999
L_isxdigit_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
tolower:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_tolower_76:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f26_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S3, SB, SC
; Spill t2 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function isupper
    CALL isupper
; Scalar return value for t3
; Copy Rv0 to allocatable S0
    ADD S0, RV0, R0
    LI T7, 0
    XOR T6, S0, T7
    LI T5, 0
    SLTU S0, T5, T6
    BEQ S0, R0, L_tolower_79
; Branch to L_tolower_79 if condition is false
    BEQ R0, R0, L_tolower_77
; Unconditional branch to L_tolower_77 (condition was true)
L_tolower_77:
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f26_op6_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    LI T2, 65
    SUB T3, T3, T2
    LI T1, 97
    ADD T3, T3, T1
    MOVE RV0, T3
; Jump to epilogue
    BEQ R0, R0, L_tolower_99999
; Invalidated 1 alloca bindings
L_tolower_79:
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f26_op8_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
    LOAD S3, SB, T0
    MOVE RV0, S3
; Jump to epilogue
    BEQ R0, R0, L_tolower_99999
L_tolower_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
toupper:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_toupper_80:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f28_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S3, SB, SC
; Spill t2 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function islower
    CALL islower
; Scalar return value for t3
; Copy Rv0 to allocatable S0
    ADD S0, RV0, R0
    LI T7, 0
    XOR T6, S0, T7
    LI T5, 0
    SLTU S0, T5, T6
    BEQ S0, R0, L_toupper_83
; Branch to L_toupper_83 if condition is false
    BEQ R0, R0, L_toupper_81
; Unconditional branch to L_toupper_81 (condition was true)
L_toupper_81:
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f28_op6_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    LI T2, 97
    SUB T3, T3, T2
    LI T1, 65
    ADD T3, T3, T1
    MOVE RV0, T3
; Jump to epilogue
    BEQ R0, R0, L_toupper_99999
; Invalidated 1 alloca bindings
L_toupper_83:
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f28_op8_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
    LOAD S3, SB, T0
    MOVE RV0, S3
; Jump to epilogue
    BEQ R0, R0, L_toupper_99999
L_toupper_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
