; Generated by Ripple C99 Compiler (rcc)

getchar:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
    ADD S3, FP, R0
    BEQ R0, R0, L_getchar_1
; Unconditional branch to L_getchar_1
; Invalidated 1 alloca bindings
L_getchar_1:
    LI S2, 3
    ADD A0, S2, R0
; Spill live registers before call
; Spill const_f0_op0_3 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S2, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function mmio_read
    CALL mmio_read
; Scalar return value for t1
; Copy Rv0 to allocatable S1
    ADD S1, RV0, R0
; Recompute alloca t0 at FP+0
    ADD S0, FP, R0
    STORE S1, SB, S0
    BEQ R0, R0, L_getchar_2
; Unconditional branch to L_getchar_2
; Invalidated 1 alloca bindings
L_getchar_2:
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(0), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(0), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t0 at FP+0
    ADD T7, FP, R0
    LOAD T6, SB, T7
    LI T5, 1
    LI T4, 0
    SLL T5, T5, T4
    AND T6, T6, T5
    LI T3, 0
    XOR T2, T6, T3
    LI T1, 1
    SLTU T6, T2, T1
    LI T0, 0
    XOR S3, T6, T0
    LI S2, 0
    SLTU T6, S2, S3
    BEQ T6, R0, L_getchar_3
; Branch to L_getchar_3 if condition is false
    BEQ R0, R0, L_getchar_1
; Unconditional branch to L_getchar_1 (condition was true)
; Invalidated 1 alloca bindings
L_getchar_3:
    LI S0, 2
    ADD A0, S0, R0
; Spill live registers before call
; Spill t1 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Spill const_f0_op8_2 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function mmio_read
    CALL mmio_read
; Scalar return value for t7
; Copy Rv0 to allocatable T4
    ADD T4, RV0, R0
    MOVE RV0, T4
; Jump to epilogue
    BEQ R0, R0, L_getchar_99999
L_getchar_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
