; Generated by Ripple C99 Compiler (rcc)

print_char:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S3, SB, SC
; Spill t2 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function putchar
    CALL putchar
    LI RV0, 1
; Jump to epilogue
    BEQ R0, R0, L_print_char_99999
L_print_char_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
print_str:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 11 slots for locals
    ADDI SP, SP, 11
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
; Copy param 0 bank from A1
    ADD S2, A1, R0
L_print_str_1:
    ADD S1, FP, R0
; Store fat ptr to stack alloca t1 at FP+0
    ADDI SC, FP, 0
    STORE S3, SB, SC
    ADDI SC, SC, 1
    STORE S2, SB, SC
    ADD S0, FP, R0
    ADDI S0, S0, 2
    LI T7, 0
    STORE T7, SB, S0
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op7_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T6, SB, S1
    ADDI T5, S1, 1
    LOAD T4, SB, T5
; Bank value in T4 - tags: -1 = Global, -2 = Stack, positive = dynamic
    LI T3, 0
    XOR T2, T6, T3
    LI T1, 1
    SLTU T6, T2, T1
    BEQ T6, R0, L_print_str_4
; Branch to L_print_str_4 if condition is false
    BEQ R0, R0, L_print_str_2
; Unconditional branch to L_print_str_2 (condition was true)
; Invalidated 2 alloca bindings
L_print_str_2:
    LI RV0, 0
; Jump to epilogue
    BEQ R0, R0, L_print_str_99999
L_print_str_4:
    BEQ R0, R0, L_print_str_5
; Unconditional branch to L_print_str_5
L_print_str_5:
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op13_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
    LOAD T7, SB, T0
    ADDI T5, T0, 1
    LOAD T2, SB, T5
; Bank value in T2 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(5), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Mixed })
; LOAD: Pointer t5 has bank info: Dynamic("load_f2_op16_t5_bank_val")
    LI T3, -1
    BEQ T2, T3, L_bc_087fe2fd_use_global
    LI T6, -2
    BEQ T2, T6, L_bc_087fe2fd_use_stack
    ADD T1, T2, R0
    BEQ R0, R0, L_bc_087fe2fd_done
L_bc_087fe2fd_use_global:
    ADD T1, GP, R0
    BEQ R0, R0, L_bc_087fe2fd_done
L_bc_087fe2fd_use_stack:
    ADD T1, SB, R0
L_bc_087fe2fd_done:
; LOAD: Using bank register T1 for load
    LOAD S0, T1, T7
    BEQ S0, R0, L_print_str_7
; Branch to L_print_str_7 if condition is false
    BEQ R0, R0, L_print_str_6
; Unconditional branch to L_print_str_6 (condition was true)
; Invalidated 1 alloca bindings
L_print_str_6:
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op21_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD S1, FP, R0
    LOAD T5, SB, S1
    ADDI T3, S1, 1
    LOAD T6, SB, T3
; Bank value in T6 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(7), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(7), bank: Mixed })
; LOAD: Pointer t7 has bank info: Dynamic("load_f2_op24_t7_bank_val")
    LI T0, -1
    BEQ T6, T0, L_bc_c8cbf2af_use_global
    LI T3, -2
    BEQ T6, T3, L_bc_c8cbf2af_use_stack
    ADD S0, T6, R0
    BEQ R0, R0, L_bc_c8cbf2af_done
L_bc_c8cbf2af_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_c8cbf2af_done
L_bc_c8cbf2af_use_stack:
    ADD S0, SB, R0
L_bc_c8cbf2af_done:
; LOAD: Using bank register S0 for load
    LOAD T0, S0, T5
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S3, SB, SC
; Spill param_bank_f2_op3_0 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE S2, SB, SC
; Spill param_bank_f2_op3_0 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE S2, SB, SC
; Spill load_f2_op10_t3_bank_val to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE T4, SB, SC
; Spill t5 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 15
    STORE T7, SB, SC
; Spill load_f2_op16_t5_bank_val to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE T2, SB, SC
; Spill load_f2_op16_t5_bank_val to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE T2, SB, SC
; Spill load_f2_op17_t6_resolved_bank_2_f2_op18 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 18
    STORE T1, SB, SC
; Spill t7 to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 19
    STORE T5, SB, SC
; Spill load_f2_op24_t7_bank_val to slot 9
    ADD SC, FP, R0
    ADDI SC, SC, 20
    STORE T6, SB, SC
; Spill load_f2_op24_t7_bank_val to slot 10
    ADD SC, FP, R0
    ADDI SC, SC, 21
    STORE T6, SB, SC
; Spill load_f2_op25_t8_resolved_bank_2_f2_op26 to slot 11
    ADD SC, FP, R0
    ADDI SC, SC, 22
    STORE S0, SB, SC
; Spill t8 to slot 12
    ADD SC, FP, R0
    ADDI SC, SC, 23
    STORE T0, SB, SC
; Set SP = FP+31 so callee frame is above spills
    ADDI SP, FP, 31
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T0, R0
; Call function putchar
    CALL putchar
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op29_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD S3, SB, T3
    ADDI S2, T3, 1
    LOAD T4, SB, S2
; Bank value in T4 - tags: -1 = Global, -2 = Stack, positive = dynamic
    ADDI T7, S3, 1
; WARNING: Static bank overflow - offset 1 crosses 0 banks
; GEP: Setting bank info for t10 to Dynamic("load_f2_op32_t9_bank_val")
; Store fat ptr to stack alloca t1 at FP+0
    ADDI SC, FP, 0
    STORE T7, SB, SC
    ADDI SC, SC, 1
    STORE T4, SB, SC
; Load instruction: t11 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op33_t11 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T2, FP, R0
    ADDI T2, T2, 2
    LOAD T1, SB, T2
    LI S1, 1
    ADD T1, T1, S1
    STORE T1, SB, T2
    BEQ R0, R0, L_print_str_5
; Unconditional branch to L_print_str_5
; Invalidated 2 alloca bindings
L_print_str_7:
; Load instruction: t13 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op36_t13 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T5, FP, R0
    ADDI T5, T5, 2
    LOAD T6, SB, T5
    MOVE RV0, T6
; Jump to epilogue
    BEQ R0, R0, L_print_str_99999
L_print_str_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
digit_char:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_digit_char_8:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
    LI S0, 10
    SLTU S1, S1, S0
    BEQ S1, R0, L_digit_char_11
; Branch to L_digit_char_11 if condition is false
    BEQ R0, R0, L_digit_char_9
; Unconditional branch to L_digit_char_9 (condition was true)
; Invalidated 1 alloca bindings
L_digit_char_9:
; Load instruction: t4 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op4_t4 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T7, FP, R0
    LOAD T6, SB, T7
    LI T5, 48
    ADD T5, T5, T6
    MOVE RV0, T5
; Jump to epilogue
    BEQ R0, R0, L_digit_char_99999
; Invalidated 1 alloca bindings
L_digit_char_11:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op6_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    LI T2, 10
    SUB T3, T3, T2
    LI T1, 97
    ADD T1, T1, T3
    MOVE RV0, T1
; Jump to epilogue
    BEQ R0, R0, L_digit_char_99999
L_digit_char_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
print_uint:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 28 slots for locals
    ADDI SP, SP, 28
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
; Load param 1 from A1
    ADD S2, A1, R0
L_print_uint_12:
    ADD S1, FP, R0
    STORE S3, SB, S1
    ADD S0, FP, R0
    ADDI S0, S0, 1
    STORE S2, SB, S0
    ADD T7, FP, R0
    ADDI T7, T7, 2
    ADD T6, FP, R0
    ADDI T6, T6, 18
    ADD T5, FP, R0
    ADDI T5, T5, 19
    LI T4, 0
    STORE T4, SB, T6
    LI T3, 0
    STORE T3, SB, T5
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op8_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T2, SB, S1
    LI T1, 0
    XOR T0, T2, T1
    LI T4, 1
    SLTU T2, T0, T4
    BEQ T2, R0, L_print_uint_15
; Branch to L_print_uint_15 if condition is false
    BEQ R0, R0, L_print_uint_13
; Unconditional branch to L_print_uint_13 (condition was true)
; Invalidated 5 alloca bindings
L_print_uint_13:
    LI T3, 48
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 28
    STORE S3, SB, SC
; Spill t1 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 29
    STORE S2, SB, SC
; Spill const_f6_op12_48 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 30
    STORE T3, SB, SC
; Set SP = FP+48 so callee frame is above spills
    ADDI SP, FP, 48
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T3, R0
; Call function print_char
    CALL print_char
; Scalar return value for t9
; Jump to epilogue
    BEQ R0, R0, L_print_uint_99999
L_print_uint_15:
    BEQ R0, R0, L_print_uint_16
; Unconditional branch to L_print_uint_16
L_print_uint_16:
; Load instruction: t10 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op13_t10 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+0
    ADD T0, FP, R0
    LOAD T4, SB, T0
    LI T1, 0
    SLTU T4, T1, T4
    BEQ T4, R0, L_print_uint_18
; Branch to L_print_uint_18 if condition is false
    BEQ R0, R0, L_print_uint_17
; Unconditional branch to L_print_uint_17 (condition was true)
; Invalidated 1 alloca bindings
L_print_uint_17:
; Load instruction: t12 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op15_t12 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t5 at FP+18
    ADD T2, FP, R0
    ADDI T2, T2, 18
    LOAD T5, SB, T2
; Recompute alloca t4 at FP+2
    ADD T6, FP, R0
    ADDI T6, T6, 2
    ADD S0, T5, R0
    ADD T7, T6, S0
; Runtime bank overflow calculation for dynamic GEP
    LI S3, -1536
    DIV S1, T7, S3
    MOD S2, T7, S3
; Base bank info: Stack
; Clearing binding for 'gep_new_bank_f6_op21_t13'
; Computing new bank gep_new_bank_f6_op21_t13 = SB + bank_delta
    ADD T3, SB, S1
; Result bank tracked as Dynamic(gep_new_bank_f6_op21_t13)
    ADD T7, S2, R0
; GEP: Setting bank info for t13 to Dynamic("gep_new_bank_f6_op21_t13")
; Load instruction: t14 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op22_t14 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+0
    ADD T1, FP, R0
    LOAD T4, SB, T1
; Load instruction: t15 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op24_t15 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+1
    ADD T0, FP, R0
    ADDI T0, T0, 1
    LOAD S0, SB, T0
    MOD T4, T4, S0
; Spill live registers before call
; Spill t9 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 31
    STORE RV0, SB, SC
; Spill t12 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 32
    STORE T5, SB, SC
; Spill gep_new_bank_f6_op21_t13 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 33
    STORE T3, SB, SC
; Spill t13 to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 34
    STORE T7, SB, SC
; Spill t16 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 35
    STORE T4, SB, SC
; Set SP = FP+48 so callee frame is above spills
    ADDI SP, FP, 48
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T4, R0
; Call function digit_char
    CALL digit_char
; Scalar return value for t17
; Reload t13 from slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 34
    LOAD S1, SB, SC
; Reload gep_new_bank_f6_op21_t13 from slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 33
    LOAD S3, SB, SC
    LI S0, -1
    BEQ S3, S0, L_bc_f38155ed_use_global
    LI T2, -2
    BEQ S3, T2, L_bc_f38155ed_use_stack
    ADD S2, S3, R0
    BEQ R0, R0, L_bc_f38155ed_done
L_bc_f38155ed_use_global:
    ADD S2, GP, R0
    BEQ R0, R0, L_bc_f38155ed_done
L_bc_f38155ed_use_stack:
    ADD S2, SB, R0
L_bc_f38155ed_done:
    STORE RV0, S2, S1
; Load instruction: t18 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op30_t18 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t5 at FP+18
    ADD T6, FP, R0
    ADDI T6, T6, 18
    LOAD T5, SB, T6
    LI T3, 1
    ADD T5, T5, T3
    STORE T5, SB, T6
; Load instruction: t20 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op33_t20 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+0
    ADD T7, FP, R0
    LOAD T1, SB, T7
; Load instruction: t21 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op35_t21 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+1
    ADD T0, FP, R0
    ADDI T0, T0, 1
    LOAD T4, SB, T0
    DIV T1, T1, T4
    STORE T1, SB, T7
    BEQ R0, R0, L_print_uint_16
; Unconditional branch to L_print_uint_16
; Invalidated 3 alloca bindings
L_print_uint_18:
    BEQ R0, R0, L_print_uint_19
; Unconditional branch to L_print_uint_19
L_print_uint_19:
; Load instruction: t23 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op38_t23 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t5 at FP+18
    ADD S0, FP, R0
    ADDI S0, S0, 18
    LOAD T2, SB, S0
    BEQ T2, R0, L_print_uint_21
; Branch to L_print_uint_21 if condition is false
    BEQ R0, R0, L_print_uint_20
; Unconditional branch to L_print_uint_20 (condition was true)
; Invalidated 1 alloca bindings
L_print_uint_20:
; Load instruction: t24 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op40_t24 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t5 at FP+18
    ADD T3, FP, R0
    ADDI T3, T3, 18
    LOAD T4, SB, T3
    LI T0, 1
    SUB T4, T4, T0
    STORE T4, SB, T3
; Load instruction: t26 = load FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(5), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op43_t26 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T6, SB, T3
; Recompute alloca t4 at FP+2
    ADD T7, FP, R0
    ADDI T7, T7, 2
    ADD S0, T6, R0
    ADD T2, T7, S0
; Runtime bank overflow calculation for dynamic GEP
; Spill t17 to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 36
    STORE RV0, SB, SC
    LI RV0, -1536
    DIV T0, T2, RV0
; Spill t13 to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 34
    STORE S1, SB, SC
; Spill gep_new_bank_f6_op21_t13 to slot 9
    ADD SC, FP, R0
    ADDI SC, SC, 37
    STORE S3, SB, SC
    MOD S1, T2, RV0
; Base bank info: Stack
; Clearing binding for 'gep_new_bank_f6_op49_t27'
; Spill gep_new_bank_f6_op21_t13 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 33
    STORE S3, SB, SC
; Computing new bank gep_new_bank_f6_op49_t27 = SB + bank_delta
    ADD S3, SB, T0
; Result bank tracked as Dynamic(gep_new_bank_f6_op49_t27)
    ADD T2, S1, R0
; GEP: Setting bank info for t27 to Dynamic("gep_new_bank_f6_op49_t27")
; Load instruction: t28 = load FatPtr(FatPointer { addr: Temp(27), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(27), bank: Mixed })
; LOAD: Pointer t27 has bank info: Dynamic("gep_new_bank_f6_op49_t27")
    LI T0, -1
    BEQ S3, T0, L_bc_0563c60d_use_global
    LI RV0, -2
    BEQ S3, RV0, L_bc_0563c60d_use_stack
    ADD S0, S3, R0
    BEQ R0, R0, L_bc_0563c60d_done
L_bc_0563c60d_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_0563c60d_done
L_bc_0563c60d_use_stack:
    ADD S0, SB, R0
L_bc_0563c60d_done:
; LOAD: Using bank register S0 for load
    LOAD S1, S0, T2
; Spill live registers before call
; Spill store_f6_op26_resolved_bank_6_f6_op27 to slot 10
    ADD SC, FP, R0
    ADDI SC, SC, 38
    STORE S2, SB, SC
; Spill t19 to slot 11
    ADD SC, FP, R0
    ADDI SC, SC, 39
    STORE T5, SB, SC
; Spill t22 to slot 12
    ADD SC, FP, R0
    ADDI SC, SC, 40
    STORE T1, SB, SC
; Spill t25 to slot 13
    ADD SC, FP, R0
    ADDI SC, SC, 41
    STORE T4, SB, SC
; Spill t26 to slot 14
    ADD SC, FP, R0
    ADDI SC, SC, 42
    STORE T6, SB, SC
; Spill t27 to slot 15
    ADD SC, FP, R0
    ADDI SC, SC, 43
    STORE T2, SB, SC
; Spill gep_new_bank_f6_op49_t27 to slot 16
    ADD SC, FP, R0
    ADDI SC, SC, 44
    STORE S3, SB, SC
; Spill gep_new_bank_f6_op49_t27 to slot 17
    ADD SC, FP, R0
    ADDI SC, SC, 45
    STORE S3, SB, SC
; Spill load_f6_op50_t28_resolved_bank_6_f6_op51 to slot 18
    ADD SC, FP, R0
    ADDI SC, SC, 46
    STORE S0, SB, SC
; Spill t28 to slot 19
    ADD SC, FP, R0
    ADDI SC, SC, 47
    STORE S1, SB, SC
; Set SP = FP+48 so callee frame is above spills
    ADDI SP, FP, 48
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function print_char
    CALL print_char
; Scalar return value for t29
; Load instruction: t30 = load FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op54_t30 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t6 at FP+19
    ADD T0, FP, R0
    ADDI T0, T0, 19
    LOAD S2, SB, T0
    LI T5, 1
    ADD S2, S2, T5
    STORE S2, SB, T0
    BEQ R0, R0, L_print_uint_19
; Unconditional branch to L_print_uint_19
; Invalidated 1 alloca bindings
L_print_uint_21:
; Load instruction: t32 = load FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(6), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op57_t32 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t6 at FP+19
    ADD T1, FP, R0
    ADDI T1, T1, 19
    LOAD T4, SB, T1
    MOVE RV0, T4
; Jump to epilogue
    BEQ R0, R0, L_print_uint_99999
L_print_uint_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
print_int:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 11 slots for locals
    ADDI SP, SP, 11
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_print_int_22:
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
    ADD S0, FP, R0
    ADDI S0, S0, 2
; Load instruction: t4 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op2_t4 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T7, SB, S2
    LI T6, 0
    SLT T7, T7, T6
    BEQ T7, R0, L_print_int_25
; Branch to L_print_int_25 if condition is false
    BEQ R0, R0, L_print_int_23
; Unconditional branch to L_print_int_23 (condition was true)
; Invalidated 3 alloca bindings
L_print_int_23:
    LI T5, 45
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S3, SB, SC
; Spill const_f8_op4_45 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T5, SB, SC
; Set SP = FP+31 so callee frame is above spills
    ADDI SP, FP, 31
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T5, R0
; Call function print_char
    CALL print_char
; Scalar return value for t6
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op5_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    LI T2, 0
    SUB T2, T2, T3
; Recompute alloca t3 at FP+2
    ADD T1, FP, R0
    ADDI T1, T1, 2
    STORE T2, SB, T1
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op8_t9 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T0, SB, T1
    LI T6, 10
; Spill live registers before call
; Spill t6 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE RV0, SB, SC
; Spill t8 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE T2, SB, SC
; Spill t9 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 15
    STORE T0, SB, SC
; Spill const_f8_op10_10 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE T6, SB, SC
; Set SP = FP+31 so callee frame is above spills
    ADDI SP, FP, 31
; Setting up 2 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T0, R0
; Arg 1 (scalar) to A1
    ADD A1, T6, R0
; Call function print_uint
    CALL print_uint
; Scalar return value for t10
    LI T7, 1
    ADD T7, T7, RV0
    MOVE RV0, T7
; Jump to epilogue
    BEQ R0, R0, L_print_int_99999
L_print_int_25:
; Load instruction: t12 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op11_t12 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD S0, FP, R0
    LOAD S1, SB, S0
    LI S2, 10
; Spill live registers before call
; Spill t11 to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE T7, SB, SC
; Spill t12 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 18
    STORE S1, SB, SC
; Spill const_f8_op13_10 to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 19
    STORE S2, SB, SC
; Set SP = FP+31 so callee frame is above spills
    ADDI SP, FP, 31
; Setting up 2 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Arg 1 (scalar) to A1
    ADD A1, S2, R0
; Call function print_uint
    CALL print_uint
; Scalar return value for t13
; Recompute alloca t2 at FP+1
    ADD S3, FP, R0
    ADDI S3, S3, 1
    STORE RV0, SB, S3
; Load instruction: t14 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f8_op15_t14 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T5, SB, S3
    MOVE RV0, T5
; Jump to epilogue
    BEQ R0, R0, L_print_int_99999
L_print_int_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
printf:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 16 slots for locals
    ADDI SP, SP, 16
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
; Copy param 0 bank from A1
    ADD S2, A1, R0
L_printf_26:
    ADD S1, FP, R0
; Store fat ptr to stack alloca t1 at FP+0
    ADDI SC, FP, 0
    STORE S3, SB, SC
    ADDI SC, SC, 1
    STORE S2, SB, SC
    ADD S0, FP, R0
    ADDI S0, S0, 2
    ADD T7, FP, R0
    ADDI T7, T7, 4
    ADD T6, FP, R0
    ADDI T6, T6, 6
; va_start: first extra at FP-7
    ADDI T5, FP, -7
    LI T4, -2
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE T5, SB, SC
    ADDI SC, SC, 1
    STORE T4, SB, SC
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op7_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T3, SB, S1
    ADDI T2, S1, 1
    LOAD T1, SB, T2
; Bank value in T1 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Store fat ptr to stack alloca t3 at FP+4
    ADDI SC, FP, 4
    STORE T3, SB, SC
    ADDI SC, SC, 1
    STORE T1, SB, SC
    LI T0, 0
    STORE T0, SB, T6
    BEQ R0, R0, L_printf_27
; Unconditional branch to L_printf_27
; Invalidated 4 alloca bindings
L_printf_27:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op13_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD T4, FP, R0
    ADDI T4, T4, 4
    LOAD T2, SB, T4
    ADDI T0, T4, 1
    LOAD T6, SB, T0
; Bank value in T6 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(6), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(6), bank: Mixed })
; LOAD: Pointer t6 has bank info: Dynamic("load_f10_op16_t6_bank_val")
    LI S0, -1
    BEQ T6, S0, L_bc_b415d4bb_use_global
    LI S1, -2
    BEQ T6, S1, L_bc_b415d4bb_use_stack
    ADD T7, T6, R0
    BEQ R0, R0, L_bc_b415d4bb_done
L_bc_b415d4bb_use_global:
    ADD T7, GP, R0
    BEQ R0, R0, L_bc_b415d4bb_done
L_bc_b415d4bb_use_stack:
    ADD T7, SB, R0
L_bc_b415d4bb_done:
; LOAD: Using bank register T7 for load
    LOAD T0, T7, T2
    BEQ T0, R0, L_printf_29
; Branch to L_printf_29 if condition is false
    BEQ R0, R0, L_printf_28
; Unconditional branch to L_printf_28 (condition was true)
; Invalidated 1 alloca bindings
L_printf_28:
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op21_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD S0, FP, R0
    ADDI S0, S0, 4
    LOAD S1, SB, S0
    ADDI T0, S0, 1
    LOAD T4, SB, T0
; Bank value in T4 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t9 = load FatPtr(FatPointer { addr: Temp(8), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(8), bank: Mixed })
; LOAD: Pointer t8 has bank info: Dynamic("load_f10_op24_t8_bank_val")
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE S3, SB, SC
; Spill param_bank_f10_op3_0 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE S2, SB, SC
    LI S3, -1
    BEQ T4, S3, L_bc_07c78b9c_use_global
; Spill param_bank_f10_op3_0 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 18
    STORE S2, SB, SC
    LI S2, -2
    BEQ T4, S2, L_bc_07c78b9c_use_stack
    ADD T0, T4, R0
    BEQ R0, R0, L_bc_07c78b9c_done
L_bc_07c78b9c_use_global:
    ADD T0, GP, R0
    BEQ R0, R0, L_bc_07c78b9c_done
L_bc_07c78b9c_use_stack:
    ADD T0, SB, R0
L_bc_07c78b9c_done:
; LOAD: Using bank register T0 for load
    LOAD S3, T0, S1
    LI S2, 37
; Spill t1048581 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 19
    STORE T5, SB, SC
    XOR T5, S3, S2
; Spill t5 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 20
    STORE T3, SB, SC
; Spill load_f10_op10_t5_bank_val to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 21
    STORE T1, SB, SC
    LI T3, 1
    SLTU S3, T5, T3
    BEQ S3, R0, L_printf_31
; Branch to L_printf_31 if condition is false
    BEQ R0, R0, L_printf_30
; Unconditional branch to L_printf_30 (condition was true)
; Invalidated 1 alloca bindings
L_printf_30:
; Load instruction: t11 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op31_t11 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD T5, FP, R0
    ADDI T5, T5, 4
    LOAD T3, SB, T5
    ADDI S2, T5, 1
    LOAD S3, SB, S2
; Bank value in S3 - tags: -1 = Global, -2 = Stack, positive = dynamic
    ADDI S0, T3, 1
; WARNING: Static bank overflow - offset 1 crosses 0 banks
; GEP: Setting bank info for t12 to Dynamic("load_f10_op34_t11_bank_val")
; Store fat ptr to stack alloca t3 at FP+4
    ADDI SC, FP, 4
    STORE S0, SB, SC
    ADDI SC, SC, 1
    STORE S3, SB, SC
; Load instruction: t13 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op35_t13 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S2, SB, T5
; Spill load_f10_op10_t5_bank_val to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 22
    STORE T1, SB, SC
    ADDI T1, T5, 1
; Spill t6 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 23
    STORE T2, SB, SC
; Spill load_f10_op16_t6_bank_val to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 24
    STORE T6, SB, SC
    LOAD T2, SB, T1
; Bank value in T2 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t14 = load FatPtr(FatPointer { addr: Temp(13), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(13), bank: Mixed })
; LOAD: Pointer t13 has bank info: Dynamic("load_f10_op38_t13_bank_val")
; Spill load_f10_op16_t6_bank_val to slot 9
    ADD SC, FP, R0
    ADDI SC, SC, 25
    STORE T6, SB, SC
    LI T6, -1
    BEQ T2, T6, L_bc_387cffc8_use_global
; Spill load_f10_op17_t7_resolved_bank_10_f10_op18 to slot 10
    ADD SC, FP, R0
    ADDI SC, SC, 26
    STORE T7, SB, SC
    LI T7, -2
    BEQ T2, T7, L_bc_387cffc8_use_stack
    ADD T1, T2, R0
    BEQ R0, R0, L_bc_387cffc8_done
L_bc_387cffc8_use_global:
    ADD T1, GP, R0
    BEQ R0, R0, L_bc_387cffc8_done
L_bc_387cffc8_use_stack:
    ADD T1, SB, R0
L_bc_387cffc8_done:
; LOAD: Using bank register T1 for load
    LOAD T6, T1, S2
    LI T7, 0
; Spill t8 to slot 11
    ADD SC, FP, R0
    ADDI SC, SC, 27
    STORE S1, SB, SC
; Spill load_f10_op24_t8_bank_val to slot 12
    ADD SC, FP, R0
    ADDI SC, SC, 28
    STORE T4, SB, SC
    XOR S1, T6, T7
; Spill load_f10_op24_t8_bank_val to slot 13
    ADD SC, FP, R0
    ADDI SC, SC, 29
    STORE T4, SB, SC
    LI T4, 1
    SLTU T6, S1, T4
    BEQ T6, R0, L_printf_35
; Branch to L_printf_35 if condition is false
    BEQ R0, R0, L_printf_33
; Unconditional branch to L_printf_33 (condition was true)
; Invalidated 1 alloca bindings
L_printf_33:
; Load instruction: t16 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op45_t16 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD S1, FP, R0
    ADDI S1, S1, 6
    LOAD T4, SB, S1
    LI T7, 37
; Spill live registers before call
; Spill load_f10_op25_t9_resolved_bank_10_f10_op26 to slot 14
    ADD SC, FP, R0
    ADDI SC, SC, 30
    STORE T0, SB, SC
; Spill t11 to slot 15
    ADD SC, FP, R0
    ADDI SC, SC, 31
    STORE T3, SB, SC
; Spill load_f10_op34_t11_bank_val to slot 16
    ADD SC, FP, R0
    ADDI SC, SC, 32
    STORE S3, SB, SC
; Spill t12 to slot 17
    ADD SC, FP, R0
    ADDI SC, SC, 33
    STORE S0, SB, SC
; Spill load_f10_op34_t11_bank_val to slot 18
    ADD SC, FP, R0
    ADDI SC, SC, 34
    STORE S3, SB, SC
; Spill load_f10_op34_t11_bank_val to slot 19
    ADD SC, FP, R0
    ADDI SC, SC, 35
    STORE S3, SB, SC
; Spill t13 to slot 20
    ADD SC, FP, R0
    ADDI SC, SC, 36
    STORE S2, SB, SC
; Spill load_f10_op38_t13_bank_val to slot 21
    ADD SC, FP, R0
    ADDI SC, SC, 37
    STORE T2, SB, SC
; Spill load_f10_op38_t13_bank_val to slot 22
    ADD SC, FP, R0
    ADDI SC, SC, 38
    STORE T2, SB, SC
; Spill load_f10_op39_t14_resolved_bank_10_f10_op40 to slot 23
    ADD SC, FP, R0
    ADDI SC, SC, 39
    STORE T1, SB, SC
; Spill t16 to slot 24
    ADD SC, FP, R0
    ADDI SC, SC, 40
    STORE T4, SB, SC
; Spill const_f10_op47_37 to slot 25
    ADD SC, FP, R0
    ADDI SC, SC, 41
    STORE T7, SB, SC
; Set SP = FP+42 so callee frame is above spills
    ADDI SP, FP, 42
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T7, R0
; Call function print_char
    CALL print_char
; Scalar return value for t17
; Reload t16 from slot 24
    ADD SC, FP, R0
    ADDI SC, SC, 40
    LOAD T6, SB, SC
    ADD T6, T6, RV0
; Recompute alloca t4 at FP+6
    ADD T5, FP, R0
    ADDI T5, T5, 6
    STORE T6, SB, T5
    BEQ R0, R0, L_printf_29
; Unconditional branch to L_printf_29
; Invalidated 1 alloca bindings
L_printf_35:
; Load instruction: t19 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op49_t19 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD T0, FP, R0
    ADDI T0, T0, 4
    LOAD T3, SB, T0
    ADDI S0, T0, 1
    LOAD S3, SB, S0
; Bank value in S3 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t20 = load FatPtr(FatPointer { addr: Temp(19), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(19), bank: Mixed })
; LOAD: Pointer t19 has bank info: Dynamic("load_f10_op52_t19_bank_val")
    LI T2, -1
    BEQ S3, T2, L_bc_8f52dfe4_use_global
    LI T1, -2
    BEQ S3, T1, L_bc_8f52dfe4_use_stack
    ADD S2, S3, R0
    BEQ R0, R0, L_bc_8f52dfe4_done
L_bc_8f52dfe4_use_global:
    ADD S2, GP, R0
    BEQ R0, R0, L_bc_8f52dfe4_done
L_bc_8f52dfe4_use_stack:
    ADD S2, SB, R0
L_bc_8f52dfe4_done:
; LOAD: Using bank register S2 for load
    LOAD S1, S2, T3
    ADD T4, FP, R0
    ADDI T4, T4, 7
    STORE S1, SB, T4
; Load instruction: t22 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op58_t22 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T7, SB, T4
    LI RV0, 37
    XOR T5, T7, RV0
    LI S0, 1
    SLTU T7, T5, S0
    BEQ T7, R0, L_printf_44
; Branch to L_printf_44 if condition is false
    BEQ R0, R0, L_printf_41
; Unconditional branch to L_printf_41 (condition was true)
; Invalidated 2 alloca bindings
L_printf_44:
; Load instruction: t24 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op62_t24 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t21 at FP+7
    ADD T2, FP, R0
    ADDI T2, T2, 7
    LOAD T1, SB, T2
    LI T5, 99
    XOR S0, T1, T5
    LI RV0, 1
    SLTU T1, S0, RV0
    BEQ T1, R0, L_printf_45
; Branch to L_printf_45 if condition is false
    BEQ R0, R0, L_printf_37
; Unconditional branch to L_printf_37 (condition was true)
; Invalidated 1 alloca bindings
L_printf_45:
; Load instruction: t26 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op66_t26 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t21 at FP+7
    ADD T7, FP, R0
    ADDI T7, T7, 7
    LOAD T0, SB, T7
    LI T4, 100
    XOR S0, T0, T4
    LI RV0, 1
    SLTU T0, S0, RV0
    BEQ T0, R0, L_printf_46
; Branch to L_printf_46 if condition is false
    BEQ R0, R0, L_printf_38
; Unconditional branch to L_printf_38 (condition was true)
; Invalidated 1 alloca bindings
L_printf_46:
; Load instruction: t28 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op70_t28 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t21 at FP+7
    ADD T5, FP, R0
    ADDI T5, T5, 7
    LOAD T1, SB, T5
    LI T2, 115
    XOR S0, T1, T2
    LI RV0, 1
    SLTU T1, S0, RV0
    BEQ T1, R0, L_printf_47
; Branch to L_printf_47 if condition is false
    BEQ R0, R0, L_printf_36
; Unconditional branch to L_printf_36 (condition was true)
; Invalidated 1 alloca bindings
L_printf_47:
; Load instruction: t30 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op74_t30 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t21 at FP+7
    ADD T4, FP, R0
    ADDI T4, T4, 7
    LOAD T0, SB, T4
    LI T7, 117
    XOR S0, T0, T7
    LI RV0, 1
    SLTU T0, S0, RV0
    BEQ T0, R0, L_printf_48
; Branch to L_printf_48 if condition is false
    BEQ R0, R0, L_printf_39
; Unconditional branch to L_printf_39 (condition was true)
; Invalidated 1 alloca bindings
L_printf_48:
; Load instruction: t32 = load FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(21), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op78_t32 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t21 at FP+7
    ADD T2, FP, R0
    ADDI T2, T2, 7
    LOAD T1, SB, T2
    LI T5, 120
    XOR S0, T1, T5
    LI RV0, 1
    SLTU T1, S0, RV0
    BEQ T1, R0, L_printf_49
; Branch to L_printf_49 if condition is false
    BEQ R0, R0, L_printf_40
; Unconditional branch to L_printf_40 (condition was true)
; Invalidated 1 alloca bindings
L_printf_49:
    BEQ R0, R0, L_printf_42
; Unconditional branch to L_printf_42
L_printf_50:
    BEQ R0, R0, L_printf_36
; Unconditional branch to L_printf_36
L_printf_36:
; Load instruction: t34 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op82_t34 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T7, FP, R0
    ADDI T7, T7, 6
    LOAD T0, SB, T7
; va_arg i8*
; LOAD: Pointer load_src_ptr_f10_op85_t2097236 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T4, FP, R0
    ADDI T4, T4, 2
    LOAD S0, SB, T4
    ADDI RV0, T4, 1
    LOAD T5, SB, RV0
; Bank value in T5 - tags: -1 = Global, -2 = Stack, positive = dynamic
    LOAD T1, SB, S0
    ADDI SC, S0, -1
    LOAD T2, SB, SC
    ADDI S0, S0, -2
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE S0, SB, SC
    ADDI SC, SC, 1
    STORE T5, SB, SC
; Spill live registers before call
; Spill t18 to slot 26
    ADD SC, FP, R0
    ADDI SC, SC, 42
    STORE T6, SB, SC
; Spill t19 to slot 27
    ADD SC, FP, R0
    ADDI SC, SC, 43
    STORE T3, SB, SC
; Spill load_f10_op52_t19_bank_val to slot 28
    ADD SC, FP, R0
    ADDI SC, SC, 44
    STORE S3, SB, SC
; Spill load_f10_op52_t19_bank_val to slot 29
    ADD SC, FP, R0
    ADDI SC, SC, 45
    STORE S3, SB, SC
; Spill load_f10_op53_t20_resolved_bank_10_f10_op54 to slot 30
    ADD SC, FP, R0
    ADDI SC, SC, 46
    STORE S2, SB, SC
; Spill t20 to slot 31
    ADD SC, FP, R0
    ADDI SC, SC, 47
    STORE S1, SB, SC
; Spill t34 to slot 32
    ADD SC, FP, R0
    ADDI SC, SC, 48
    STORE T0, SB, SC
; Spill t2097236 to slot 33
    ADD SC, FP, R0
    ADDI SC, SC, 49
    STORE S0, SB, SC
; Spill load_f10_op88_t2097236_bank_val to slot 34
    ADD SC, FP, R0
    ADDI SC, SC, 50
    STORE T5, SB, SC
; Spill load_f10_op88_t2097236_bank_val to slot 35
    ADD SC, FP, R0
    ADDI SC, SC, 51
    STORE T5, SB, SC
; Spill t35 to slot 36
    ADD SC, FP, R0
    ADDI SC, SC, 52
    STORE T1, SB, SC
; Spill load_f10_op89_t35_bank_val to slot 37
    ADD SC, FP, R0
    ADDI SC, SC, 53
    STORE T2, SB, SC
; Spill load_f10_op89_t35_bank_val to slot 38
    ADD SC, FP, R0
    ADDI SC, SC, 54
    STORE T2, SB, SC
; Set SP = FP+55 so callee frame is above spills
    ADDI SP, FP, 55
; Setting up 1 register arguments
; Arg 0 (fat ptr) to A0,A1
    ADD A0, T1, R0
    ADD A1, T2, R0
; Call function print_str
    CALL print_str
; Scalar return value for t36
; Reload t34 from slot 32
    ADD SC, FP, R0
    ADDI SC, SC, 48
    LOAD T6, SB, SC
    ADD T6, T6, RV0
; Recompute alloca t4 at FP+6
    ADD T3, FP, R0
    ADDI T3, T3, 6
    STORE T6, SB, T3
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_37:
; Load instruction: t38 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op91_t38 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD S3, FP, R0
    ADDI S3, S3, 6
    LOAD S2, SB, S3
; va_arg i16
; LOAD: Pointer load_src_ptr_f10_op94_t2097245 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD S1, FP, R0
    ADDI S1, S1, 2
    LOAD T7, SB, S1
    ADDI T0, S1, 1
    LOAD T4, SB, T0
; Bank value in T4 - tags: -1 = Global, -2 = Stack, positive = dynamic
; LOAD: Pointer t2097245 has bank info: Dynamic("load_f10_op97_t2097245_bank_val")
    LI T5, -1
    BEQ T4, T5, L_bc_3ede88cb_use_global
    LI T1, -2
    BEQ T4, T1, L_bc_3ede88cb_use_stack
    ADD S0, T4, R0
    BEQ R0, R0, L_bc_3ede88cb_done
L_bc_3ede88cb_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_3ede88cb_done
L_bc_3ede88cb_use_stack:
    ADD S0, SB, R0
L_bc_3ede88cb_done:
; LOAD: Using bank register S0 for load
    LOAD T2, S0, T7
    ADDI T7, T7, -1
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE T7, SB, SC
    ADDI SC, SC, 1
    STORE T4, SB, SC
; Spill live registers before call
; Spill t37 to slot 39
    ADD SC, FP, R0
    ADDI SC, SC, 55
    STORE T6, SB, SC
; Spill t38 to slot 40
    ADD SC, FP, R0
    ADDI SC, SC, 56
    STORE S2, SB, SC
; Spill load_f10_op98_t39_resolved_bank_10_f10_op99 to slot 41
    ADD SC, FP, R0
    ADDI SC, SC, 57
    STORE S0, SB, SC
; Spill t2097245 to slot 42
    ADD SC, FP, R0
    ADDI SC, SC, 58
    STORE T7, SB, SC
; Spill load_f10_op97_t2097245_bank_val to slot 43
    ADD SC, FP, R0
    ADDI SC, SC, 59
    STORE T4, SB, SC
; Spill load_f10_op97_t2097245_bank_val to slot 44
    ADD SC, FP, R0
    ADDI SC, SC, 60
    STORE T4, SB, SC
; Spill t39 to slot 45
    ADD SC, FP, R0
    ADDI SC, SC, 61
    STORE T2, SB, SC
; Set SP = FP+62 so callee frame is above spills
    ADDI SP, FP, 62
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Call function print_char
    CALL print_char
; Scalar return value for t40
; Reload t38 from slot 40
    ADD SC, FP, R0
    ADDI SC, SC, 56
    LOAD T3, SB, SC
    ADD T3, T3, RV0
; Recompute alloca t4 at FP+6
    ADD T0, FP, R0
    ADDI T0, T0, 6
    STORE T3, SB, T0
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_38:
; Load instruction: t42 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op103_t42 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T5, FP, R0
    ADDI T5, T5, 6
    LOAD T1, SB, T5
; va_arg i16
; LOAD: Pointer load_src_ptr_f10_op106_t2097257 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T6, FP, R0
    ADDI T6, T6, 2
    LOAD S3, SB, T6
    ADDI S2, T6, 1
    LOAD S1, SB, S2
; Bank value in S1 - tags: -1 = Global, -2 = Stack, positive = dynamic
; LOAD: Pointer t2097257 has bank info: Dynamic("load_f10_op109_t2097257_bank_val")
    LI T7, -1
    BEQ S1, T7, L_bc_bbf2226d_use_global
    LI T4, -2
    BEQ S1, T4, L_bc_bbf2226d_use_stack
    ADD S0, S1, R0
    BEQ R0, R0, L_bc_bbf2226d_done
L_bc_bbf2226d_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_bbf2226d_done
L_bc_bbf2226d_use_stack:
    ADD S0, SB, R0
L_bc_bbf2226d_done:
; LOAD: Using bank register S0 for load
    LOAD T2, S0, S3
    ADDI S3, S3, -1
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE S3, SB, SC
    ADDI SC, SC, 1
    STORE S1, SB, SC
; Spill live registers before call
; Spill t41 to slot 46
    ADD SC, FP, R0
    ADDI SC, SC, 62
    STORE T3, SB, SC
; Spill t42 to slot 47
    ADD SC, FP, R0
    ADDI SC, SC, 63
    STORE T1, SB, SC
; Spill load_f10_op110_t43_resolved_bank_10_f10_op111 to slot 48
    ADD SC, FP, R0
    ADDI SC, SC, 64
    STORE S0, SB, SC
; Spill t2097257 to slot 49
    ADD SC, FP, R0
    ADDI SC, SC, 65
    STORE S3, SB, SC
; Spill load_f10_op109_t2097257_bank_val to slot 50
    ADD SC, FP, R0
    ADDI SC, SC, 66
    STORE S1, SB, SC
; Spill load_f10_op109_t2097257_bank_val to slot 51
    ADD SC, FP, R0
    ADDI SC, SC, 67
    STORE S1, SB, SC
; Spill t43 to slot 52
    ADD SC, FP, R0
    ADDI SC, SC, 68
    STORE T2, SB, SC
; Set SP = FP+69 so callee frame is above spills
    ADDI SP, FP, 69
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Call function print_int
    CALL print_int
; Scalar return value for t44
; Reload t42 from slot 47
    ADD SC, FP, R0
    ADDI SC, SC, 63
    LOAD T0, SB, SC
    ADD T0, T0, RV0
; Recompute alloca t4 at FP+6
    ADD S2, FP, R0
    ADDI S2, S2, 6
    STORE T0, SB, S2
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_39:
; Load instruction: t46 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op115_t46 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T7, FP, R0
    ADDI T7, T7, 6
    LOAD T4, SB, T7
; va_arg i16
; LOAD: Pointer load_src_ptr_f10_op118_t2097269 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T3, FP, R0
    ADDI T3, T3, 2
    LOAD T5, SB, T3
    ADDI T1, T3, 1
    LOAD T6, SB, T1
; Bank value in T6 - tags: -1 = Global, -2 = Stack, positive = dynamic
; LOAD: Pointer t2097269 has bank info: Dynamic("load_f10_op121_t2097269_bank_val")
    LI S3, -1
    BEQ T6, S3, L_bc_c96afc88_use_global
    LI S1, -2
    BEQ T6, S1, L_bc_c96afc88_use_stack
    ADD S0, T6, R0
    BEQ R0, R0, L_bc_c96afc88_done
L_bc_c96afc88_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_c96afc88_done
L_bc_c96afc88_use_stack:
    ADD S0, SB, R0
L_bc_c96afc88_done:
; LOAD: Using bank register S0 for load
    LOAD T2, S0, T5
    ADDI T5, T5, -1
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE T5, SB, SC
    ADDI SC, SC, 1
    STORE T6, SB, SC
    LI RV0, 10
; Spill live registers before call
; Spill t45 to slot 53
    ADD SC, FP, R0
    ADDI SC, SC, 69
    STORE T0, SB, SC
; Spill t46 to slot 54
    ADD SC, FP, R0
    ADDI SC, SC, 70
    STORE T4, SB, SC
; Spill load_f10_op122_t47_resolved_bank_10_f10_op123 to slot 55
    ADD SC, FP, R0
    ADDI SC, SC, 71
    STORE S0, SB, SC
; Spill t2097269 to slot 56
    ADD SC, FP, R0
    ADDI SC, SC, 72
    STORE T5, SB, SC
; Spill load_f10_op121_t2097269_bank_val to slot 57
    ADD SC, FP, R0
    ADDI SC, SC, 73
    STORE T6, SB, SC
; Spill load_f10_op121_t2097269_bank_val to slot 58
    ADD SC, FP, R0
    ADDI SC, SC, 74
    STORE T6, SB, SC
; Spill t47 to slot 59
    ADD SC, FP, R0
    ADDI SC, SC, 75
    STORE T2, SB, SC
; Spill const_f10_op126_10 to slot 60
    ADD SC, FP, R0
    ADDI SC, SC, 76
    STORE RV0, SB, SC
; Set SP = FP+77 so callee frame is above spills
    ADDI SP, FP, 77
; Setting up 2 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Arg 1 (scalar) to A1
    ADD A1, RV0, R0
; Call function print_uint
    CALL print_uint
; Scalar return value for t48
; Reload t46 from slot 54
    ADD SC, FP, R0
    ADDI SC, SC, 70
    LOAD S2, SB, SC
    ADD S2, S2, RV0
; Recompute alloca t4 at FP+6
    ADD T1, FP, R0
    ADDI T1, T1, 6
    STORE S2, SB, T1
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_40:
; Load instruction: t50 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op128_t50 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD S3, FP, R0
    ADDI S3, S3, 6
    LOAD S1, SB, S3
; va_arg i16
; LOAD: Pointer load_src_ptr_f10_op131_t2097282 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t2 at FP+2
    ADD T0, FP, R0
    ADDI T0, T0, 2
    LOAD T7, SB, T0
    ADDI T4, T0, 1
    LOAD T3, SB, T4
; Bank value in T3 - tags: -1 = Global, -2 = Stack, positive = dynamic
; LOAD: Pointer t2097282 has bank info: Dynamic("load_f10_op134_t2097282_bank_val")
    LI T5, -1
    BEQ T3, T5, L_bc_691655f1_use_global
    LI T6, -2
    BEQ T3, T6, L_bc_691655f1_use_stack
    ADD S0, T3, R0
    BEQ R0, R0, L_bc_691655f1_done
L_bc_691655f1_use_global:
    ADD S0, GP, R0
    BEQ R0, R0, L_bc_691655f1_done
L_bc_691655f1_use_stack:
    ADD S0, SB, R0
L_bc_691655f1_done:
; LOAD: Using bank register S0 for load
    LOAD T2, S0, T7
    ADDI T7, T7, -1
; Store fat ptr to stack alloca t2 at FP+2
    ADDI SC, FP, 2
    STORE T7, SB, SC
    ADDI SC, SC, 1
    STORE T3, SB, SC
    LI RV0, 16
; Spill live registers before call
; Spill t49 to slot 61
    ADD SC, FP, R0
    ADDI SC, SC, 77
    STORE S2, SB, SC
; Spill t50 to slot 62
    ADD SC, FP, R0
    ADDI SC, SC, 78
    STORE S1, SB, SC
; Spill load_f10_op135_t51_resolved_bank_10_f10_op136 to slot 63
    ADD SC, FP, R0
    ADDI SC, SC, 79
    STORE S0, SB, SC
; Spill t2097282 to slot 64
    ADD SC, FP, R0
    ADDI SC, SC, 80
    STORE T7, SB, SC
; Spill load_f10_op134_t2097282_bank_val to slot 65
    ADD SC, FP, R0
    ADDI SC, SC, 81
    STORE T3, SB, SC
; Spill load_f10_op134_t2097282_bank_val to slot 66
    ADD SC, FP, R0
    ADDI SC, SC, 82
    STORE T3, SB, SC
; Spill t51 to slot 67
    ADD SC, FP, R0
    ADDI SC, SC, 83
    STORE T2, SB, SC
; Spill const_f10_op139_16 to slot 68
    ADD SC, FP, R0
    ADDI SC, SC, 84
    STORE RV0, SB, SC
; Set SP = FP+85 so callee frame is above spills
    ADDI SP, FP, 85
; Setting up 2 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T2, R0
; Arg 1 (scalar) to A1
    ADD A1, RV0, R0
; Call function print_uint
    CALL print_uint
; Scalar return value for t52
; Reload t50 from slot 62
    ADD SC, FP, R0
    ADDI SC, SC, 78
    LOAD T1, SB, SC
    ADD T1, T1, RV0
; Recompute alloca t4 at FP+6
    ADD T4, FP, R0
    ADDI T4, T4, 6
    STORE T1, SB, T4
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_41:
; Load instruction: t54 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op141_t54 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T5, FP, R0
    ADDI T5, T5, 6
    LOAD T6, SB, T5
    LI S2, 37
; Spill live registers before call
; Spill t53 to slot 69
    ADD SC, FP, R0
    ADDI SC, SC, 85
    STORE T1, SB, SC
; Spill t54 to slot 70
    ADD SC, FP, R0
    ADDI SC, SC, 86
    STORE T6, SB, SC
; Spill const_f10_op143_37 to slot 71
    ADD SC, FP, R0
    ADDI SC, SC, 87
    STORE S2, SB, SC
; Set SP = FP+88 so callee frame is above spills
    ADDI SP, FP, 88
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S2, R0
; Call function print_char
    CALL print_char
; Scalar return value for t55
; Reload t54 from slot 70
    ADD SC, FP, R0
    ADDI SC, SC, 86
    LOAD S3, SB, SC
    ADD S3, S3, RV0
; Recompute alloca t4 at FP+6
    ADD S1, FP, R0
    ADDI S1, S1, 6
    STORE S3, SB, S1
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_42:
; Load instruction: t57 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op145_t57 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T0, FP, R0
    ADDI T0, T0, 6
    LOAD S0, SB, T0
    LI T7, 37
; Spill live registers before call
; Spill t56 to slot 72
    ADD SC, FP, R0
    ADDI SC, SC, 88
    STORE S3, SB, SC
; Spill t57 to slot 73
    ADD SC, FP, R0
    ADDI SC, SC, 89
    STORE S0, SB, SC
; Spill const_f10_op147_37 to slot 74
    ADD SC, FP, R0
    ADDI SC, SC, 90
    STORE T7, SB, SC
; Set SP = FP+91 so callee frame is above spills
    ADDI SP, FP, 91
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T7, R0
; Call function print_char
    CALL print_char
; Scalar return value for t58
; Reload t57 from slot 73
    ADD SC, FP, R0
    ADDI SC, SC, 89
    LOAD T3, SB, SC
    ADD T3, T3, RV0
; Recompute alloca t4 at FP+6
    ADD T2, FP, R0
    ADDI T2, T2, 6
    STORE T3, SB, T2
; Load instruction: t60 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op149_t60 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T4, SB, T2
; Load instruction: t61 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op151_t61 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD T1, FP, R0
    ADDI T1, T1, 4
    LOAD T5, SB, T1
    ADDI T6, T1, 1
    LOAD S2, SB, T6
; Bank value in S2 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t62 = load FatPtr(FatPointer { addr: Temp(61), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(61), bank: Mixed })
; LOAD: Pointer t61 has bank info: Dynamic("load_f10_op154_t61_bank_val")
    LI S3, -1
    BEQ S2, S3, L_bc_a64fcc1e_use_global
    LI T0, -2
    BEQ S2, T0, L_bc_a64fcc1e_use_stack
    ADD S1, S2, R0
    BEQ R0, R0, L_bc_a64fcc1e_done
L_bc_a64fcc1e_use_global:
    ADD S1, GP, R0
    BEQ R0, R0, L_bc_a64fcc1e_done
L_bc_a64fcc1e_use_stack:
    ADD S1, SB, R0
L_bc_a64fcc1e_done:
; LOAD: Using bank register S1 for load
    LOAD S0, S1, T5
; Spill live registers before call
; Spill t59 to slot 75
    ADD SC, FP, R0
    ADDI SC, SC, 91
    STORE T3, SB, SC
; Spill t60 to slot 76
    ADD SC, FP, R0
    ADDI SC, SC, 92
    STORE T4, SB, SC
; Spill t61 to slot 77
    ADD SC, FP, R0
    ADDI SC, SC, 93
    STORE T5, SB, SC
; Spill load_f10_op154_t61_bank_val to slot 78
    ADD SC, FP, R0
    ADDI SC, SC, 94
    STORE S2, SB, SC
; Spill load_f10_op154_t61_bank_val to slot 79
    ADD SC, FP, R0
    ADDI SC, SC, 95
    STORE S2, SB, SC
; Spill load_f10_op155_t62_resolved_bank_10_f10_op156 to slot 80
    ADD SC, FP, R0
    ADDI SC, SC, 96
    STORE S1, SB, SC
; Spill t62 to slot 81
    ADD SC, FP, R0
    ADDI SC, SC, 97
    STORE S0, SB, SC
; Set SP = FP+98 so callee frame is above spills
    ADDI SP, FP, 98
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function print_char
    CALL print_char
; Scalar return value for t63
; Reload t60 from slot 76
    ADD SC, FP, R0
    ADDI SC, SC, 92
    LOAD T7, SB, SC
    ADD T7, T7, RV0
; Recompute alloca t4 at FP+6
    ADD T6, FP, R0
    ADDI T6, T6, 6
    STORE T7, SB, T6
    BEQ R0, R0, L_printf_43
; Unconditional branch to L_printf_43
; Invalidated 1 alloca bindings
L_printf_43:
    BEQ R0, R0, L_printf_32
; Unconditional branch to L_printf_32
L_printf_31:
; Load instruction: t65 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op160_t65 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD S3, FP, R0
    ADDI S3, S3, 6
    LOAD T0, SB, S3
; Load instruction: t66 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op162_t66 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD T3, FP, R0
    ADDI T3, T3, 4
    LOAD T2, SB, T3
    ADDI T4, T3, 1
    LOAD T1, SB, T4
; Bank value in T1 - tags: -1 = Global, -2 = Stack, positive = dynamic
; Load instruction: t67 = load FatPtr(FatPointer { addr: Temp(66), bank: Mixed })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(66), bank: Mixed })
; LOAD: Pointer t66 has bank info: Dynamic("load_f10_op165_t66_bank_val")
    LI S2, -1
    BEQ T1, S2, L_bc_d91dabaf_use_global
    LI S1, -2
    BEQ T1, S1, L_bc_d91dabaf_use_stack
    ADD T5, T1, R0
    BEQ R0, R0, L_bc_d91dabaf_done
L_bc_d91dabaf_use_global:
    ADD T5, GP, R0
    BEQ R0, R0, L_bc_d91dabaf_done
L_bc_d91dabaf_use_stack:
    ADD T5, SB, R0
L_bc_d91dabaf_done:
; LOAD: Using bank register T5 for load
    LOAD S0, T5, T2
; Spill live registers before call
; Spill t64 to slot 82
    ADD SC, FP, R0
    ADDI SC, SC, 98
    STORE T7, SB, SC
; Spill t65 to slot 83
    ADD SC, FP, R0
    ADDI SC, SC, 99
    STORE T0, SB, SC
; Spill t66 to slot 84
    ADD SC, FP, R0
    ADDI SC, SC, 100
    STORE T2, SB, SC
; Spill load_f10_op165_t66_bank_val to slot 85
    ADD SC, FP, R0
    ADDI SC, SC, 101
    STORE T1, SB, SC
; Spill load_f10_op165_t66_bank_val to slot 86
    ADD SC, FP, R0
    ADDI SC, SC, 102
    STORE T1, SB, SC
; Spill load_f10_op166_t67_resolved_bank_10_f10_op167 to slot 87
    ADD SC, FP, R0
    ADDI SC, SC, 103
    STORE T5, SB, SC
; Spill t67 to slot 88
    ADD SC, FP, R0
    ADDI SC, SC, 104
    STORE S0, SB, SC
; Set SP = FP+105 so callee frame is above spills
    ADDI SP, FP, 105
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function print_char
    CALL print_char
; Scalar return value for t68
; Reload t65 from slot 83
    ADD SC, FP, R0
    ADDI SC, SC, 99
    LOAD T6, SB, SC
    ADD T6, T6, RV0
; Recompute alloca t4 at FP+6
    ADD T4, FP, R0
    ADDI T4, T4, 6
    STORE T6, SB, T4
    BEQ R0, R0, L_printf_32
; Unconditional branch to L_printf_32
; Invalidated 1 alloca bindings
L_printf_32:
; Load instruction: t70 = load FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(3), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op171_t70 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t3 at FP+4
    ADD S2, FP, R0
    ADDI S2, S2, 4
    LOAD S1, SB, S2
    ADDI T7, S2, 1
    LOAD S3, SB, T7
; Bank value in S3 - tags: -1 = Global, -2 = Stack, positive = dynamic
    ADDI T0, S1, 1
; WARNING: Static bank overflow - offset 1 crosses 0 banks
; GEP: Setting bank info for t71 to Dynamic("load_f10_op174_t70_bank_val")
; Store fat ptr to stack alloca t3 at FP+4
    ADDI SC, FP, 4
    STORE T0, SB, SC
    ADDI SC, SC, 1
    STORE S3, SB, SC
    BEQ R0, R0, L_printf_27
; Unconditional branch to L_printf_27
; Invalidated 1 alloca bindings
L_printf_29:
; Load instruction: t72 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f10_op175_t72 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t4 at FP+6
    ADD T3, FP, R0
    ADDI T3, T3, 6
    LOAD T2, SB, T3
    MOVE RV0, T2
; Jump to epilogue
    BEQ R0, R0, L_printf_99999
L_printf_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
