; Generated by Ripple C99 Compiler (rcc)

.data
__gp_rand:
.space 1
.code
; Global 'rand_initialized' at address 0
srand:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, FP, R0
    STORE S3, SB, S2
    ADD S1, FP, R0
    ADDI S1, S1, 1
; Load instruction: t3 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t3 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S2
    LI T7, 0
    LI T6, -1
    LI T5, 0
    AND T4, S0, T6
    AND T3, T7, T5
    STORE T4, SB, S1
    ADDI SC, S1, 1
    STORE T3, SB, SC
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(2), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op8_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T2, SB, S1
    ADD A0, T2, R0
; Spill live registers before call
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t3 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Spill i32_zext_0_f0_op4 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T7, SB, SC
; Spill const_f0_op5_65535 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T6, SB, SC
; Spill i32_const_hi_0_f0_op6 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE T5, SB, SC
; Spill t4 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 15
    STORE T4, SB, SC
; Spill t4__hi to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE T3, SB, SC
; Spill t5 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE T2, SB, SC
; Set SP = FP+30 so callee frame is above spills
    ADDI SP, FP, 30
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function rng_set_seed
    CALL rng_set_seed
    LI T1, 1
    LI T0, __gp_rand
    STORE T1, GP, T0
; Jump to epilogue
    BEQ R0, R0, L_srand_99999
L_srand_99999:
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
rand:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
L_rand_1:
; Load instruction: t0 = load Global("rand_initialized")
; Canonicalizing global variable: rand_initialized
    LI S3, __gp_rand
; LOAD: Pointer load_src_ptr_f2_op1_t0 has bank info: Global
; LOAD: Using bank register Gp for load
    LOAD S2, GP, S3
    LI S1, 0
    XOR S0, S2, S1
    LI T7, 0
    SLTU S2, T7, S0
    LI T6, 0
    XOR T5, S2, T6
    LI T4, 1
    SLTU S2, T5, T4
    LI T3, 0
    XOR T2, S2, T3
    LI T1, 0
    SLTU S2, T1, T2
    BEQ S2, R0, L_rand_4
; Branch to L_rand_4 if condition is false
    BEQ R0, R0, L_rand_2
; Unconditional branch to L_rand_2 (condition was true)
L_rand_2:
    LI T0, 1
    ADD A0, T0, R0
; Spill live registers before call
; Spill load_f2_op0_t0_addr to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S3, SB, SC
; Spill const_f2_op9_1 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE T0, SB, SC
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function srand
    CALL srand
    BEQ R0, R0, L_rand_4
; Unconditional branch to L_rand_4
L_rand_4:
    ADD S0, FP, R0
; Spill live registers before call
; Set SP = FP+29 so callee frame is above spills
    ADDI SP, FP, 29
; Call function rng_get
    CALL rng_get
; Scalar return value for t5
; Copy Rv0 to allocatable T7
    ADD T7, RV0, R0
; Recompute alloca t4 at FP+0
    ADD S1, FP, R0
    STORE T7, SB, S1
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(4), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op11_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T5, SB, S1
    LI T4, 32767
    AND T5, T5, T4
    MOVE RV0, T5
; Jump to epilogue
    BEQ R0, R0, L_rand_99999
L_rand_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
