; Generated by Ripple C99 Compiler (rcc)

abs:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
    LI S0, 0
    SLT S1, S1, S0
    BEQ S1, R0, L_abs_3
; Branch to L_abs_3 if condition is false
    BEQ R0, R0, L_abs_1
; Unconditional branch to L_abs_1 (condition was true)
; Invalidated 1 alloca bindings
L_abs_1:
; Load instruction: t4 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op4_t4 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T7, FP, R0
    LOAD T6, SB, T7
    LI T5, 0
    SUB T5, T5, T6
    MOVE RV0, T5
; Jump to epilogue
    BEQ R0, R0, L_abs_99999
; Invalidated 1 alloca bindings
L_abs_3:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op6_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    MOVE RV0, T3
; Jump to epilogue
    BEQ R0, R0, L_abs_99999
L_abs_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
labs:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
; Copy param 0 high/bank from A1
    ADD S2, A1, R0
L_labs_4:
    ADD S1, FP, R0
    STORE S3, SB, S1
    ADDI SC, S1, 1
    STORE S2, SB, SC
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op4_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S1
    ADDI SC, S1, 1
    LOAD T7, SB, SC
    LI T6, 0
    LI T5, 0
    XOR T4, T7, T5
    BNE T4, R0, L_i32_slt_hine_3841d4e4_2_0
    SLTU T4, S0, T6
    BEQ R0, R0, L_i32_slt_done_3841d4e4_2_1
L_i32_slt_hine_3841d4e4_2_0:
    SLT T4, T7, T5
L_i32_slt_done_3841d4e4_2_1:
    BEQ T4, R0, L_labs_7
; Branch to L_labs_7 if condition is false
    BEQ R0, R0, L_labs_5
; Unconditional branch to L_labs_5 (condition was true)
; Invalidated 1 alloca bindings
L_labs_5:
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op6_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
    LOAD T2, SB, T3
    ADDI SC, T3, 1
    LOAD T1, SB, SC
    LI T0, 0
    LI T4, 0
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t0__hi to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S2, SB, SC
    SLTU S2, T0, T2
    SUB S1, T0, T2
    SUB S3, T4, T1
    SUB S3, S3, S2
    MOVE RV0, S1
    MOVE RV1, S3
; Jump to epilogue
    BEQ R0, R0, L_labs_99999
; Invalidated 1 alloca bindings
L_labs_7:
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op11_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T3, FP, R0
; Spill t2 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE S0, SB, SC
    LOAD S0, SB, T3
; Spill t2__hi to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T7, SB, SC
    ADDI SC, T3, 1
    LOAD T7, SB, SC
    MOVE RV0, S0
    MOVE RV1, T7
; Jump to epilogue
    BEQ R0, R0, L_labs_99999
L_labs_99999:
; Return fat pointer
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
exit:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_exit_8:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
    HALT
; Jump to epilogue
    BEQ R0, R0, L_exit_99999
L_exit_99999:
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
abort:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 8 slots for locals
    ADDI SP, SP, 8
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
L_abort_9:
    LI S3, 97
; Spill live registers before call
; Spill const_f6_op0_97 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 8
    STORE S3, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S3, R0
; Call function putchar
    CALL putchar
    LI S2, 98
; Spill live registers before call
; Spill const_f6_op1_98 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S2, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S2, R0
; Call function putchar
    CALL putchar
    LI S1, 111
; Spill live registers before call
; Spill const_f6_op2_111 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S1, R0
; Call function putchar
    CALL putchar
    LI S0, 114
; Spill live registers before call
; Spill const_f6_op3_114 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, S0, R0
; Call function putchar
    CALL putchar
    LI T7, 116
; Spill live registers before call
; Spill const_f6_op4_116 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T7, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T7, R0
; Call function putchar
    CALL putchar
    LI T6, 10
; Spill live registers before call
; Spill const_f6_op5_10 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T6, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
    ADD A0, T6, R0
; Call function putchar
    CALL putchar
    HALT
; Jump to epilogue
    BEQ R0, R0, L_abort_99999
L_abort_99999:
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    ADD PCB, RAB, R0
    JALR R0, R0, RA
