; Generated by Ripple C99 Compiler (rcc)

abs:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
    LI S0, 0
    SLT S1, S1, S0
    LI T7, 0
    XOR T6, S1, T7
    LI T5, 0
    SLTU S1, T5, T6
    BEQ S1, R0, L_abs_3
; Branch to L_abs_3 if condition is false
    BEQ R0, R0, L_abs_1
; Unconditional branch to L_abs_1 (condition was true)
; Invalidated 1 alloca bindings
L_abs_1:
; Load instruction: t5 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op6_t5 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T4, FP, R0
    LOAD T3, SB, T4
    LI T2, 0
    SUB T2, T2, T3
    MOVE RV0, T2
; Jump to epilogue
    BEQ R0, R0, L_abs_99999
; Invalidated 1 alloca bindings
L_abs_3:
; Load instruction: t7 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f0_op8_t7 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T1, FP, R0
    LOAD T0, SB, T1
    MOVE RV0, T0
; Jump to epilogue
    BEQ R0, R0, L_abs_99999
L_abs_99999:
; Return scalar value
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
labs:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 10 slots for locals
    ADDI SP, SP, 10
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
; Copy param 0 high/bank from A1
    ADD S2, A1, R0
L_labs_4:
    ADD S1, FP, R0
    STORE S3, SB, S1
    ADDI SC, S1, 1
    STORE S2, SB, SC
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op4_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S0, SB, S1
    ADDI SC, S1, 1
    LOAD T7, SB, SC
    LI T6, 0
    LI T5, 0
    XOR T4, T7, T5
    BNE T4, R0, L_i32_slt_hine_117b809c_2_0
    SLTU T4, S0, T6
    BEQ R0, R0, L_i32_slt_done_117b809c_2_1
L_i32_slt_hine_117b809c_2_0:
    SLT T4, T7, T5
L_i32_slt_done_117b809c_2_1:
    LI T3, 0
    XOR T2, T4, T3
    LI T1, 0
    SLTU T4, T1, T2
    BEQ T4, R0, L_labs_7
; Branch to L_labs_7 if condition is false
    BEQ R0, R0, L_labs_5
; Unconditional branch to L_labs_5 (condition was true)
; Invalidated 1 alloca bindings
L_labs_5:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op8_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
    LOAD T2, SB, T0
    ADDI SC, T0, 1
    LOAD T1, SB, SC
    LI T3, 0
    LI T4, 0
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S3, SB, SC
; Spill t0__hi to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S2, SB, SC
    SLTU S2, T3, T2
    SUB S1, T3, T2
    SUB S3, T4, T1
    SUB S3, S3, S2
    MOVE RV0, S1
    MOVE RV1, S3
; Jump to epilogue
    BEQ R0, R0, L_labs_99999
; Invalidated 1 alloca bindings
L_labs_7:
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f2_op13_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
; Spill t2 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE S0, SB, SC
    LOAD S0, SB, T0
; Spill t2__hi to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T7, SB, SC
    ADDI SC, T0, 1
    LOAD T7, SB, SC
    MOVE RV0, S0
    MOVE RV1, T7
; Jump to epilogue
    BEQ R0, R0, L_labs_99999
L_labs_99999:
; Return fat pointer
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
llabs:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 12 slots for locals
    ADDI SP, SP, 12
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
    ADD S2, A1, R0
    ADD S1, A2, R0
    ADD S0, A3, R0
L_llabs_8:
    ADD T7, FP, R0
    STORE S3, SB, T7
    ADDI SC, T7, 1
    STORE S2, SB, SC
    ADDI SC, T7, 2
    STORE S1, SB, SC
    ADDI SC, T7, 3
    STORE S0, SB, SC
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op3_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD T6, SB, T7
    ADDI SC, T7, 1
    LOAD T5, SB, SC
    ADDI SC, T7, 2
    LOAD T4, SB, SC
    ADDI SC, T7, 3
    LOAD T3, SB, SC
    LI T2, 0
    LI T1, 0
    LI T0, 0
; Spill t0 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE S3, SB, SC
    LI S3, 0
; Spill t0__w1 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE S2, SB, SC
    ADD S2, T2, R0
; Spill t0__w2 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 14
    STORE S1, SB, SC
    ADD S1, T1, R0
; Spill t0__w3 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 15
    STORE S0, SB, SC
    ADD S0, T0, R0
    ADD T7, S3, R0
; Spill i64_c0_4_f4_op5 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 16
    STORE T2, SB, SC
    XOR T2, T3, T7
    BNE T2, R0, L_i64_slt_w3ne_dadec39d_4_0
    XOR T2, T4, S0
    BNE T2, R0, L_i64_slt_w2ne_dadec39d_4_1
    XOR T2, T5, S1
    BNE T2, R0, L_i64_slt_w1ne_dadec39d_4_2
    SLTU T2, T6, S2
    BEQ R0, R0, L_i64_slt_done_dadec39d_4_3
L_i64_slt_w3ne_dadec39d_4_0:
    SLT T2, T3, T7
    BEQ R0, R0, L_i64_slt_done_dadec39d_4_3
L_i64_slt_w2ne_dadec39d_4_1:
    SLTU T2, T4, S0
    BEQ R0, R0, L_i64_slt_done_dadec39d_4_3
L_i64_slt_w1ne_dadec39d_4_2:
    SLTU T2, T5, S1
L_i64_slt_done_dadec39d_4_3:
; Spill i64_c1_4_f4_op6 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 17
    STORE T1, SB, SC
    LI T1, 0
; Spill i64_c2_4_f4_op7 to slot 6
    ADD SC, FP, R0
    ADDI SC, SC, 18
    STORE T0, SB, SC
    XOR T0, T2, T1
; Spill i64_c3_4_f4_op8 to slot 7
    ADD SC, FP, R0
    ADDI SC, SC, 19
    STORE S3, SB, SC
    LI S3, 0
    SLTU T2, S3, T0
    BEQ T2, R0, L_llabs_11
; Branch to L_llabs_11 if condition is false
    BEQ R0, R0, L_llabs_9
; Unconditional branch to L_llabs_9 (condition was true)
L_llabs_9:
; Load instruction: t6 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op11_t6 has bank info: Stack
; LOAD: Using bank register Sb for load
; Recompute alloca t1 at FP+0
    ADD T0, FP, R0
    LOAD S3, SB, T0
    ADDI SC, T0, 1
    LOAD T1, SB, SC
    ADDI SC, T0, 2
    LOAD T2, SB, SC
; Spill t2 to slot 8
    ADD SC, FP, R0
    ADDI SC, SC, 20
    STORE T6, SB, SC
    ADDI SC, T0, 3
    LOAD T6, SB, SC
; Spill t2__w1 to slot 9
    ADD SC, FP, R0
    ADDI SC, SC, 21
    STORE T5, SB, SC
    LI T5, 0
; Spill t2__w2 to slot 10
    ADD SC, FP, R0
    ADDI SC, SC, 22
    STORE T4, SB, SC
    LI T4, 0
; Spill t2__w3 to slot 11
    ADD SC, FP, R0
    ADDI SC, SC, 23
    STORE T3, SB, SC
    LI T3, 0
; Spill t3 to slot 12
    ADD SC, FP, R0
    ADDI SC, SC, 24
    STORE S2, SB, SC
    LI S2, 0
    ADD RV0, T5, R0
    ADD RV1, T4, R0
    ADD X0, T3, R0
    ADD X1, S2, R0
    ADD A0, S3, R0
    ADD A1, T1, R0
    ADD A2, T2, R0
    ADD A3, T6, R0
; Spill t3__w1 to slot 13
    ADD SC, FP, R0
    ADDI SC, SC, 25
    STORE S1, SB, SC
; Spill t3__w2 to slot 14
    ADD SC, FP, R0
    ADDI SC, SC, 26
    STORE S0, SB, SC
; Spill t3__w3 to slot 15
    ADD SC, FP, R0
    ADDI SC, SC, 27
    STORE T7, SB, SC
    LI SC, 0
    SLTU X2, RV0, A0
    SUB X3, RV0, A0
    SUB S1, X3, SC
    SLTU X3, X3, SC
    OR SC, X2, X3
    SLTU X2, RV1, A1
    SUB X3, RV1, A1
    SUB S0, X3, SC
    SLTU X3, X3, SC
    OR SC, X2, X3
    SLTU X2, X0, A2
    SUB X3, X0, A2
    SUB T7, X3, SC
    SLTU X3, X3, SC
    OR SC, X2, X3
    SLTU X2, X1, A3
    SUB X3, X1, A3
    SUB T0, X3, SC
    SLTU X3, X3, SC
    OR SC, X2, X3
    MOVE RV0, S1
    MOVE RV1, S0
    MOVE X0, T7
    MOVE X1, T0
; Jump to epilogue
    BEQ R0, R0, L_llabs_99999
L_llabs_11:
; Load instruction: t8 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f4_op17_t8 has bank info: Stack
; LOAD: Using bank register Sb for load
; Spill i64_c0_4_f4_op13 to slot 16
    ADD SC, FP, R0
    ADDI SC, SC, 28
    STORE T5, SB, SC
; Recompute alloca t1 at FP+0
    ADD T5, FP, R0
; Spill i64_c1_4_f4_op14 to slot 17
    ADD SC, FP, R0
    ADDI SC, SC, 29
    STORE T4, SB, SC
    LOAD T4, SB, T5
; Spill i64_c2_4_f4_op15 to slot 18
    ADD SC, FP, R0
    ADDI SC, SC, 30
    STORE T3, SB, SC
    ADDI SC, T5, 1
    LOAD T3, SB, SC
; Spill i64_c3_4_f4_op16 to slot 19
    ADD SC, FP, R0
    ADDI SC, SC, 31
    STORE S2, SB, SC
    ADDI SC, T5, 2
    LOAD S2, SB, SC
; Spill t6 to slot 20
    ADD SC, FP, R0
    ADDI SC, SC, 32
    STORE S3, SB, SC
    ADDI SC, T5, 3
    LOAD S3, SB, SC
    MOVE RV0, T4
    MOVE RV1, T3
    MOVE X0, S2
    MOVE X1, S3
; Jump to epilogue
    BEQ R0, R0, L_llabs_99999
L_llabs_99999:
; Return fat pointer
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
exit:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 9 slots for locals
    ADDI SP, SP, 9
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
; Load param 0 from A0
    ADD S3, A0, R0
L_exit_12:
    ADD S2, FP, R0
    STORE S3, SB, S2
; Load instruction: t2 = load FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; Canonicalizing fat pointer: FatPtr(FatPointer { addr: Temp(1), bank: Stack })
; LOAD: Pointer load_src_ptr_f6_op2_t2 has bank info: Stack
; LOAD: Using bank register Sb for load
    LOAD S1, SB, S2
    HALT
; Jump to epilogue
    BEQ R0, R0, L_exit_99999
L_exit_99999:
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
abort:
; === Function Prologue ===
; Save RA at SP
    STORE RA, SB, SP
    ADDI SP, SP, 1
; Save RAB at SP
    STORE RAB, SB, SP
    ADDI SP, SP, 1
; Save old FP
    STORE FP, SB, SP
    ADDI SP, SP, 1
; Save callee-saved registers S0-S3
    STORE S0, SB, SP
    ADDI SP, SP, 1
    STORE S1, SB, SP
    ADDI SP, SP, 1
    STORE S2, SB, SP
    ADDI SP, SP, 1
    STORE S3, SB, SP
    ADDI SP, SP, 1
; Set FP = SP
    ADD FP, SP, R0
; Allocate 8 slots for locals
    ADDI SP, SP, 8
; Reserve 20 spill slots above locals
    ADDI SP, SP, 20
L_abort_13:
    LI S3, 97
    ADD A0, S3, R0
; Spill live registers before call
; Spill const_f8_op0_97 to slot 0
    ADD SC, FP, R0
    ADDI SC, SC, 8
    STORE S3, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    LI S2, 98
    ADD A0, S2, R0
; Spill live registers before call
; Spill const_f8_op1_98 to slot 1
    ADD SC, FP, R0
    ADDI SC, SC, 9
    STORE S2, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    LI S1, 111
    ADD A0, S1, R0
; Spill live registers before call
; Spill const_f8_op2_111 to slot 2
    ADD SC, FP, R0
    ADDI SC, SC, 10
    STORE S1, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    LI S0, 114
    ADD A0, S0, R0
; Spill live registers before call
; Spill const_f8_op3_114 to slot 3
    ADD SC, FP, R0
    ADDI SC, SC, 11
    STORE S0, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    LI T7, 116
    ADD A0, T7, R0
; Spill live registers before call
; Spill const_f8_op4_116 to slot 4
    ADD SC, FP, R0
    ADDI SC, SC, 12
    STORE T7, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    LI T6, 10
    ADD A0, T6, R0
; Spill live registers before call
; Spill const_f8_op5_10 to slot 5
    ADD SC, FP, R0
    ADDI SC, SC, 13
    STORE T6, SB, SC
; Set SP = FP+28 so callee frame is above spills
    ADDI SP, FP, 28
; Setting up 1 register arguments
; Arg 0 (scalar) to A0
; Call function putchar
    CALL putchar
    HALT
; Jump to epilogue
    BEQ R0, R0, L_abort_99999
L_abort_99999:
; === Function Epilogue ===
; Restore SP = FP
    ADD SP, FP, R0
; Restore callee-saved registers S3-S0
    ADDI SC, FP, -1
    LOAD S3, SB, SC
    ADDI SC, FP, -2
    LOAD S2, SB, SC
    ADDI SC, FP, -3
    LOAD S1, SB, SC
    ADDI SC, FP, -4
    LOAD S0, SB, SC
; Restore old FP
    ADDI SP, SP, -5
    LOAD FP, SB, SP
; Restore RAB
    ADDI SP, SP, -1
    LOAD RAB, SB, SP
; Restore RA
    ADDI SP, SP, -1
    LOAD RA, SB, SP
; Return to caller
    JALR R0, RAB, RA
